// 角色页样式工厂。从 src/CharacterScreen.js 原样外提（无行为变化），
// 供主屏幕与 character/ 下的子组件共用同一套样式。

import { Platform, StyleSheet } from 'react-native';

export const createCharacterStyles = (theme, fonts, tokens) => StyleSheet.create({
  flex: { flex: 1, backgroundColor: theme.colors.background },
  container: { flex: 1, backgroundColor: theme.colors.background, padding: 18 },
  pageHeader: { marginTop: 4, marginBottom: 14 },
  // 详情页顶部返回入口（角色库 ⇄ 角色详情拆成原生栈之后新增）
  detailBackRow: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', paddingVertical: 6, marginBottom: 2 },
  detailBackText: { color: theme.colors.primarySoft, fontSize: 13, fontWeight: '700', marginLeft: 2 },
  // 详情页分段控件：横向 chips，沿用设置页 chips 的视觉语言（不引第三方库）。
  segmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  segmentChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: tokens.radius.pill,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    marginRight: 8,
    marginBottom: 6,
  },
  segmentChipActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  segmentChipText: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), fontWeight: '700' },
  segmentChipTextActive: { color: theme.colors.primaryContrast },
  // 分段内区块：标题右侧计数、区块说明、底部「添加」条（替代原折叠区的加号）
  sectionCount: { color: theme.colors.primaryMuted, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 6 },
  cardHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18), marginTop: 6, marginBottom: 4 },
  addEntryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    borderRadius: tokens.radius.md,
    paddingVertical: 9,
    marginTop: 10,
  },
  addEntryText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(13), fontWeight: '700', marginLeft: 5 },
  title: { color: theme.colors.text, fontSize: 24, fontWeight: '800', marginBottom: 6 },
  hint: { color: theme.colors.textFaint, fontSize: 13, lineHeight: 19 },
  aigcBadge: { color: theme.colors.primarySoft, fontSize: 12, fontWeight: '700', marginTop: 2 },
  // 页头「当前：名字」pill：卡片上不再用文字角标标当前角色，全名挪到这里。
  currentPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: tokens.radius.pill,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    backgroundColor: theme.colors.primaryAlpha(0.1),
    maxWidth: '100%',
  },
  currentPillDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: theme.colors.primarySoft,
    marginRight: 6,
  },
  currentPillText: { color: theme.colors.primarySoft, fontSize: 12, fontWeight: '700', flexShrink: 1 },

  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center' },
  cardTitle: { color: theme.colors.text, fontSize: 15, fontWeight: '800', marginLeft: 8 },
  presetEntryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  presetEntryLeft: { flexDirection: 'row', alignItems: 'center' },
  presetEntryText: { color: theme.colors.textMuted, fontSize: 15, marginLeft: 10 },
  presetEntryMeta: { color: theme.colors.textFaint, fontSize: 12, marginRight: 8 },
  groupList: { maxHeight: 300, marginTop: 4 },
  groupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surface,
  },
  groupAvatar: { width: 34, height: 34, borderRadius: 9, marginLeft: 10, backgroundColor: theme.colors.surfaceBorder },
  groupAvatarFallback: { alignItems: 'center', justifyContent: 'center' },
  groupName: { color: theme.colors.textMuted, fontSize: 14, marginLeft: 10, flex: 1 },
  groupPickRow: { flexGrow: 0, marginTop: 2 },
  groupPickChip: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 60,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginRight: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surface,
  },
  groupPickChipActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primarySoft },
  groupPickAvatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: theme.colors.surfaceBorder },
  groupPickAvatarFallback: { alignItems: 'center', justifyContent: 'center' },
  groupPickText: { color: theme.colors.textMuted, fontSize: 12, marginTop: 4 },
  groupPickTextActive: { color: theme.colors.primary, fontWeight: '700' },
  countBadge: {
    marginLeft: 8,
    minWidth: 22,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 11,
    backgroundColor: theme.colors.primaryAlpha(0.18),
    alignItems: 'center',
    justifyContent: 'center',
  },
  countBadgeText: { color: theme.colors.primarySoft, fontSize: 11, fontWeight: '700' },

  label: { color: theme.colors.textMuted, marginTop: 14, marginBottom: 6, fontWeight: '700', fontSize: 13 },
  fieldHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18), marginTop: 6 },
  fieldLabel: { color: theme.colors.textFaint, fontSize: 12, marginTop: 12, marginBottom: 6, fontWeight: '600' },
  inputSmall: { paddingVertical: 9, paddingHorizontal: 11 },
  multiline: { minHeight: 160, maxHeight: 340, paddingTop: 12 },
  multilineSmall: { minHeight: 80, maxHeight: 220, paddingTop: 12 },
  contentInput: { minHeight: 80, maxHeight: 220 },
  codeInput: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 13,
  },

  button: {
    flexDirection: 'row',
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: { color: theme.colors.text, fontWeight: '800', marginLeft: 8, fontSize: 15 },
  buttonDisabled: { opacity: 0.45 },
  saveButton: { marginBottom: 12 },
  searchInput: {
    backgroundColor: theme.colors.surface,
    color: theme.colors.text,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    fontSize: fonts.scaled(13),
    marginTop: 10,
  },
  characterListControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  characterListToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 9,
    borderRadius: 10,
    backgroundColor: theme.colors.primaryAlpha(0.12),
  },
  characterListToggleText: {
    color: theme.colors.primarySoft,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 5,
  },
  characterListLocate: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 9,
    borderRadius: 10,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  characterListLocateText: {
    color: theme.colors.primarySoft,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 4,
  },
  selectBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 44,
    marginTop: 10,
    paddingHorizontal: 4,
  },
  selectBarAction: {
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
  },
  selectBarText: { color: theme.colors.primaryMuted, fontSize: fonts.scaled(14), fontWeight: '700' },
  selectBarCount: { color: theme.colors.textFaint, fontSize: fonts.scaled(12) },
  selectBarDelete: {
    minHeight: 44,
    backgroundColor: theme.colors.danger,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  selectBarDeleteText: { color: theme.colors.primaryContrast, fontSize: fonts.scaled(13), fontWeight: '700' },
  emptyHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(13), marginTop: 12, textAlign: 'center' },
  characterCardCheck: {
    position: 'absolute',
    top: 8,
    left: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderWidth: 1,
    borderColor: theme.colors.primaryContrast,
  },
  characterCardCheckOn: {
    backgroundColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  characterCardPin: {
    position: 'absolute',
    bottom: 6,
    right: 6,
     width: 40,
     height: 40,
     borderRadius: 20,

    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: tokens.border.thin,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  characterCardTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 6,
    paddingBottom: 6,
  },
  characterCardTag: {
    color: theme.colors.primarySoft,
    backgroundColor: theme.colors.primaryAlpha(0.2),
    fontSize: fonts.scaled(10),
    borderRadius: 6,
    paddingHorizontal: 5,
    paddingVertical: 1,
    marginRight: 4,
    marginTop: 4,
    overflow: 'hidden',
  },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.2),
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 8,
  },
  tagChipText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), marginRight: 4 },
  tagInputRow: { flexDirection: 'row', alignItems: 'center' },
  greetingRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  greetingInput: { flex: 1, marginBottom: 0 },
  greetingRemove: { paddingHorizontal: 10, paddingVertical: 10 },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderWidth: 1,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    paddingVertical: 11,
    borderRadius: 10,
    marginTop: 4,
    marginBottom: 4,
  },
  secondaryButtonText: { color: theme.colors.primarySoft, fontWeight: '700', marginLeft: 6, fontSize: fonts.scaled(13) },
  tagInput: { flex: 1, minHeight: 40, marginRight: 8 },
  tagAdd: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  selectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
    marginLeft: 10,
  },
  selectButtonGhost: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  selectButtonText: { color: theme.colors.primaryContrast, fontSize: fonts.scaled(15), fontWeight: '700' },
  selectButtonTextGhost: { color: theme.colors.text },

  importOverlayBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  importOverlayCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.lg,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    paddingHorizontal: 24,
    paddingVertical: 28,
    alignItems: 'center',
    ...tokens.elevation(2, theme),
  },
  importOverlayTitle: {
    color: theme.colors.text,
    fontSize: fonts.scaled(17),
    fontWeight: '800',
    marginTop: 18,
    textAlign: 'center',
  },
  importOverlayHint: {
    color: theme.colors.textMuted,
    fontSize: fonts.scaled(13),
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 8,
  },
  importButton: {
    flexDirection: 'row',
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderWidth: 1,
    borderColor: theme.colors.primary,
    paddingVertical: 11,
    borderRadius: 10,
    marginTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  importButtonText: { color: theme.colors.primarySoft, fontWeight: '700', marginLeft: 8 },
  importHint: { color: theme.colors.textFaint, fontSize: 12, marginTop: 8 },
  topicButton: {
    alignSelf: 'flex-start',
    marginTop: 10,
  },

  pillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderWidth: 1,
    borderColor: theme.colors.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
  },
  pillButtonText: { color: theme.colors.primarySoft, fontWeight: '700', fontSize: 13, marginLeft: 4 },

  characterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  characterCard: {
    width: '48%',
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.md,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    overflow: 'hidden',
    marginTop: tokens.spacing.sm + 2,
    ...tokens.elevation(1, theme),
  },
  characterCardActive: {
    borderColor: theme.colors.primary,
    borderWidth: tokens.border.thick,
    backgroundColor: theme.colors.primaryAlpha(0.06),
  },
  // 封面改竖版 3:4：比 1:1 方图更像「卡」，也给名称留出叠字空间。
  characterCardImageWrap: {
    width: '100%',
    aspectRatio: 3 / 4,
    backgroundColor: theme.colors.surfaceBorder,
  },
  characterCardImage: { width: '100%', height: '100%' },
  characterCardFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.18),
  },
  // 无头像时的两段式铺底（浅→深），替代渐变库；纯 View 叠层，不新增依赖。
  characterCardFallbackDeep: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.primaryAlpha(0.06),
  },
  characterCardFallbackText: {
    color: theme.colors.primarySoft,
    fontSize: 34,
    fontWeight: '800',
    textShadowColor: theme.colors.primaryAlpha(0.4),
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  // 名称叠在封面底部：两段式遮罩保证任何头像上文字都可读（不引渐变库）。
  characterCardScrim: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '45%',
    backgroundColor: 'rgba(12,12,24,0.12)',
  },
  characterCardScrimDeep: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '24%',
    backgroundColor: 'rgba(12,12,24,0.5)',
  },
  characterCardNameOverlay: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  characterCardName: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
    flexShrink: 1,
    textShadowColor: 'rgba(0,0,0,0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  // 「当前」由文字角标改为卡面上的实心圆点（与 2px 描边同色，成套出现）。
  characterCardCurrentDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: theme.colors.primarySoft,
    marginRight: 6,
  },
  // 群聊角标：左上小圆点 + 人群图标（与角色卡同构但可区分）。
  characterCardGroupBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  characterCardBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: theme.colors.primary,
    borderRadius: tokens.radius.pill,
    paddingHorizontal: tokens.spacing.sm,
    paddingVertical: 2,
    ...tokens.elevation(2, theme),
  },
  characterCardBadgeText: { color: theme.colors.primaryContrast, fontSize: 11, fontWeight: '700' },
  characterCardDelete: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    borderRadius: tokens.radius.pill,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: tokens.border.thin,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  characterCardNameBar: {
    backgroundColor: theme.colors.surfaceAlt,
    borderTopWidth: tokens.border.thin,
    borderTopColor: theme.colors.surfaceBorder,
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  characterCardName: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '700',
    maxWidth: '100%',
    textShadowColor: theme.colors.primaryAlpha(0.15),
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  removeText: { color: theme.colors.dangerSoft, fontWeight: '700' },

  imageRow: { flexDirection: 'row', alignItems: 'center' },
  imageActions: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  avatarBox: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.surface,
    overflow: 'hidden',
    marginRight: 12,
    borderWidth: 2,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  avatarImage: { width: 56, height: 56, borderRadius: 28 },
  avatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.primaryAlpha(0.14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholderText: { color: theme.colors.primarySoft, fontSize: 22, fontWeight: '800' },
  bgPreview: {
    width: 60,
    height: 60,
    borderRadius: 12,
    marginRight: 12,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  smallButton: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginRight: 12,
  },
  smallButtonText: { color: theme.colors.primarySoft, fontWeight: '700', fontSize: 13 },

  dataSection: { marginTop: 16 },
  dataTitle: { color: theme.colors.primarySoft, fontWeight: '800', fontSize: 13, marginBottom: 8 },
  sectionCard: {
    marginTop: 12,
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center' },
  sectionTitle: { color: theme.colors.primarySoft, fontWeight: '800', marginLeft: 8, fontSize: 13 },
  sectionBody: { paddingBottom: 10 },
  addButton: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderStyle: 'dashed',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  addButtonText: { color: theme.colors.primarySoft, fontWeight: '700', marginLeft: 6 },

  tag: {
    backgroundColor: theme.colors.primaryAlpha(0.14),
    borderWidth: 1,
    borderColor: theme.colors.primaryMutedAlpha(0.3),
    borderRadius: 14,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginRight: 6,
    marginBottom: 6,
    maxWidth: '100%',
    flexShrink: 1,
  },
  tagText: { color: theme.colors.primarySoft, fontSize: 12, lineHeight: 18, fontWeight: '600', flexShrink: 1 },

  dataField: { marginBottom: 10 },
  dataFieldLabel: { color: theme.colors.textFaint, fontSize: 12, marginBottom: 3 },
  dataFieldValue: { color: theme.colors.text, fontSize: 14, lineHeight: 20 },
  dataEmpty: { color: theme.colors.textFaint, fontSize: 13, paddingVertical: 6 },
  dataMeta: { color: theme.colors.textFaint, fontSize: 12, lineHeight: 18 },
  regexUnsafeHint: {
    color: theme.colors.warning || '#f2a516',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },

  entryCard: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.colors.surface,
  },
  entryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  entryTitle: { color: theme.colors.text, fontWeight: '700', flex: 1, marginRight: 8 },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  toggleLabel: { color: theme.colors.textMuted, fontSize: 14 },
  cycleRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
  cycleButton: {
    backgroundColor: theme.colors.surface,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  cycleButtonText: { color: theme.colors.primarySoft, fontSize: 13, fontWeight: '700' },
  numberRow: { flexDirection: 'row', marginTop: 4 },
  numberField: { flex: 1, marginRight: 10 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 4 },
  chip: {
    backgroundColor: theme.colors.surface,
    borderRadius: 15,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  chipActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  chipText: { color: theme.colors.textFaint, fontSize: 13, fontWeight: '700' },
  chipTextActive: { color: theme.colors.text },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  summaryInfo: { flex: 1, marginRight: 8 },
  summaryTitle: { color: theme.colors.text, fontWeight: '700', fontSize: 14 },
  summaryMeta: { color: theme.colors.textFaint, fontSize: 12, marginTop: 2 },
  statusBadge: {
    backgroundColor: 'rgba(136,136,136,0.18)',
    borderRadius: 9,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginRight: 6,
  },
  statusBadgeText: { color: theme.colors.textFaint, fontSize: 11, fontWeight: '700' },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    padding: 20,
  },
  modalSheet: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: theme.colors.surface,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modalTitle: { color: theme.colors.text, fontSize: 16, fontWeight: '800' },
  modalDone: { color: theme.colors.primaryMuted, fontWeight: '800' },
  modalBody: { flexGrow: 0 },
});
