// ChatScreen 的样式工厂。从 src/ChatScreen.js 原样外提（无行为变化）。
// 被 ChatScreen、MessageBubble、ThinkingIndicator、ErrorBubble 共用。

import { StyleSheet } from 'react-native';

import { hexToRgba } from '../theme/themes.js';
import { resolveBubbleStyle } from './bubbleStyle.js';

export const createChatStyles = (theme, fonts, tokens, options = {}) => {
  const {
    plain: plainBubble,
    userTextColor,
    bubbleRadius,
    tailRadius,
    bubblePaddingHorizontal,
    bubblePaddingVertical,
    hasShadow,
    userBackground,
    assistantBackground,
    mediaRadius,
  } = resolveBubbleStyle(options.bubbleStyle, theme, tokens);
  return StyleSheet.create({
  aiNoticeBar: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 2,
    alignItems: 'center',
  },
  aiNoticeText: {
    color: theme.colors.textFaint,
    fontSize: 11,
    opacity: 0.7,
    textAlign: 'center',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.divider,
    backgroundColor: hexToRgba(theme.colors.background, theme.id === 'light' ? 0.92 : 0.85),
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.sm,
  },
  selectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 62,
    paddingVertical: 6,
    paddingHorizontal: tokens.spacing.sm,
    borderRadius: tokens.radius.md,
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primaryMutedAlpha(0.3),
  },
  selectionActionText: {
    color: theme.colors.primarySoft,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 4,
  },
  selectionDeleteText: {
    color: theme.colors.danger,
  },
  selectionDeleteAction: {
    backgroundColor: theme.colors.dangerAlpha(0.14),
    borderColor: theme.colors.dangerAlpha(0.35),
  },
  selectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.xs,
  },
  selectionCount: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  characterChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: tokens.spacing.sm,
    paddingVertical: 5,
    paddingHorizontal: tokens.spacing.sm,
    borderRadius: tokens.radius.bubble,
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primaryMutedAlpha(0.25),
  },
  characterAvatar: { width: 26, height: 26, borderRadius: tokens.radius.pill, marginRight: tokens.spacing.sm, borderWidth: tokens.border.thin, borderColor: theme.colors.primaryMutedAlpha(0.45) },
  characterAvatarFallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.surfaceBorder },
  characterName: { color: theme.colors.text, fontWeight: '700', flexShrink: 1 },
  characterCaret: { marginLeft: 6 },
  noticeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primaryMutedAlpha(0.35),
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderRadius: tokens.radius.md,
    paddingVertical: 5,
    paddingHorizontal: tokens.spacing.sm + 2,
  },
  noticeButtonText: { color: theme.colors.primarySoft, fontSize: 12, fontWeight: '700', marginLeft: tokens.spacing.xs },
  actionDisabled: { opacity: 0.5 },
  modelBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  modelSheet: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: tokens.radius.lg,
    padding: tokens.metrics.cardPadding,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.divider,
    maxHeight: '75%',
  },
  modelTitle: { color: theme.colors.text, fontSize: 17, fontWeight: '800', marginBottom: 10 },
  modelLabel: { color: theme.colors.textFaint, fontSize: 12, marginTop: tokens.spacing.sm, marginBottom: 6 },
  modelSourceRow: { flexDirection: 'row' },
  modelSourceChip: {
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 7,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    marginRight: tokens.spacing.sm,
    maxWidth: 140,
  },
  modelSourceChipActive: { backgroundColor: theme.colors.primaryAlpha(0.2), borderColor: theme.colors.primary },
  modelSourceText: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '700' },
  modelSourceTextActive: { color: theme.colors.primarySoft },
  modelListScroll: { maxHeight: 240, marginTop: 2 },
  modelOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 11,
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.surface,
  },
  modelOptionText: { color: theme.colors.text, fontSize: 14, flex: 1, marginRight: tokens.spacing.sm },
  modelEmpty: { color: theme.colors.textFaint, fontSize: 13, paddingVertical: tokens.spacing.md },
  modelClose: {
    marginTop: tokens.spacing.md,
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.sm + 2,
    paddingVertical: 10,
    alignItems: 'center',
  },
  modelCloseText: { color: theme.colors.primarySoft, fontSize: 14, fontWeight: '700' },
  localHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  localLogLink: { color: theme.colors.primarySoft, fontSize: 12, fontWeight: '700' },
  localRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.surface,
  },
  localInfo: { flex: 1, marginRight: tokens.spacing.sm },
  localName: { color: theme.colors.text, fontSize: 14 },
  localMeta: { color: theme.colors.textFaint, fontSize: 11, marginTop: 2 },
  localAction: {
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 6,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primaryMutedAlpha(0.5),
  },
  localActionActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primaryAlpha(0.18) },
  localActionText: { color: theme.colors.primarySoft, fontSize: 12, fontWeight: '700' },
  thinkingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: tokens.spacing.md,
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.surface,
  },
  thinkingLabel: { color: theme.colors.text, fontSize: 15, fontWeight: '700' },
  thinkingLevels: { flexDirection: 'row', marginTop: tokens.spacing.xs },
  thinkingLevelChip: {
    paddingHorizontal: tokens.spacing.lg + 2,
    paddingVertical: tokens.spacing.sm,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    marginRight: tokens.spacing.sm,
  },
  thinkingLevelChipActive: {
    backgroundColor: theme.colors.primaryAlpha(0.2),
    borderColor: theme.colors.primary,
  },
  thinkingLevelText: { color: theme.colors.textMuted, fontSize: 13, fontWeight: '700' },
  thinkingLevelTextActive: { color: theme.colors.primarySoft },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceAlt,
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.divider,
    paddingHorizontal: 14,
    paddingVertical: tokens.spacing.sm,
  },
  searchInput: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 14,
    paddingVertical: 6,
    marginLeft: tokens.spacing.sm,
  },
  searchCount: { color: theme.colors.textFaint, fontSize: 12, marginHorizontal: tokens.spacing.sm },
  searchNav: { paddingHorizontal: tokens.spacing.xs },
  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'center',
    padding: tokens.spacing.xl,
  },
  modalSheet: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: tokens.radius.lg,
    padding: tokens.metrics.cardPadding,
    maxHeight: '70%',
    ...tokens.elevation(2, theme),
  },
  modalTitle: { color: theme.colors.text, fontSize: 16, fontWeight: '800', marginBottom: tokens.spacing.md },
  attachMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: tokens.spacing.xs,
  },
  attachMenuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: tokens.spacing.md,
    borderTopWidth: tokens.border.thin,
    borderTopColor: theme.colors.divider,
  },
  attachMenuRowLocked: { opacity: 0.5 },
  attachMenuTextWrap: { flex: 1, marginLeft: 12, marginRight: 8 },
  attachMenuTitle: { color: theme.colors.text, fontSize: fonts.scaled(15), fontWeight: '700' },
  attachMenuTitleLocked: { color: theme.colors.textFaint },
  attachMenuHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), marginTop: 2, lineHeight: fonts.scaled(17) },
  moreBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    alignItems: 'flex-end',
    paddingTop: 64,
    paddingRight: tokens.spacing.md,
  },
  moreSheet: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: tokens.radius.md + 2,
    paddingVertical: 6,
    minWidth: 168,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    ...tokens.elevation(2, theme),
  },
  moreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  moreRowText: { color: theme.colors.textMuted, fontSize: 14, marginLeft: tokens.spacing.sm + 2 },
  moreRowTextActive: { color: theme.colors.primary },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.divider,
  },
  linkLeft: { flexDirection: 'row', alignItems: 'center' },
  chatSettingsText: { color: theme.colors.textMuted, fontSize: 15, marginLeft: tokens.spacing.sm + 2 },
  chatSettingsHint: { color: theme.colors.textFaint, fontSize: 13 },
  modalList: { maxHeight: 360 },
  modalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.md,
    paddingVertical: 10,
    paddingHorizontal: tokens.spacing.md,
    marginBottom: tokens.spacing.sm,
  },
  modalRowActive: { borderWidth: tokens.border.thin, borderColor: theme.colors.primary, backgroundColor: theme.colors.primaryAlpha(0.16) },
  modalRowAvatar: { width: tokens.metrics.avatarSm, height: tokens.metrics.avatarSm, borderRadius: tokens.radius.pill, marginRight: 10 },
  modalRowAvatarFallback: {
    width: tokens.metrics.avatarSm,
    height: tokens.metrics.avatarSm,
    borderRadius: tokens.radius.pill,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
  },
  modalRowAvatarText: { color: theme.colors.text, fontSize: 14, fontWeight: '800' },
  modalRowGroupFallback: { backgroundColor: theme.colors.surfaceBorder },
  modalRowText: { color: theme.colors.textMuted, flex: 1, marginRight: 8 },
  modalRowTextActive: { color: theme.colors.text, fontWeight: '700' },
  modalBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: tokens.radius.sm,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  modalBadgeText: { color: theme.colors.text, fontSize: 11, fontWeight: '700', marginLeft: 2 },
  selectScroll: { maxHeight: 360, marginBottom: 12 },
  selectText: { color: theme.colors.text, fontSize: 15, lineHeight: 22 },
  selectActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  selectButton: {
    paddingHorizontal: tokens.spacing.lg,
    paddingVertical: 9,
    borderRadius: tokens.radius.sm,
    backgroundColor: theme.colors.primary,
    marginLeft: tokens.spacing.sm,
  },
  selectButtonGhost: {
    backgroundColor: theme.colors.surface,
  },
  selectButtonText: { color: theme.colors.text, fontWeight: '700' },
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  messages: {
    flex: 1,
  },
  messagesContent: {
    flexGrow: 1,
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: tokens.spacing.xl,
  },
  emptyIconBadge: {
    width: 84,
    height: 84,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.14),
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primaryMutedAlpha(0.35),
    marginBottom: tokens.spacing.lg,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },
  emptyTitle: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 8,
  },
  emptyText: {
    color: theme.colors.textFaint,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  loadEarlierButton: {
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginTop: 8,
    marginBottom: 4,
    borderRadius: tokens.radius.lg,
    backgroundColor: hexToRgba(theme.colors.textFaint, 0.18),
  },
  loadEarlierText: {
    fontSize: 13,
    opacity: 0.75,
  },
  emptyGreetingButton: {
    marginTop: 14,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: tokens.radius.bubble,
    backgroundColor: theme.colors.primaryAlpha(0.14),
    borderWidth: 1,
    borderColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  emptyGreetingButtonText: {
    color: theme.colors.primarySoft,
    fontSize: 13,
    fontWeight: '700',
  },
  messageRow: {
    marginVertical: 5,
    flexDirection: 'row',
  },
   messageRowLeft: {
     justifyContent: 'flex-start',
   },
   messageRowFullWidth: {
     flexDirection: 'column',
     alignSelf: 'stretch',
     marginHorizontal: -14,
   },
   messageRowRight: {
    justifyContent: 'flex-end',
  },
  avatarContainer: {
    width: 38,
    height: 38,
    borderRadius: tokens.radius.pill,
    marginRight: tokens.spacing.sm,
    overflow: 'hidden',
    alignSelf: 'flex-start',
    marginTop: tokens.spacing.lg,
    borderWidth: 2,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 5,
  },
    avatarContainerFullWidth: {
      marginTop: 0,
      marginRight: tokens.spacing.sm,
    },
   fullWidthMessageHeader: {
     width: '100%',
     flexDirection: 'row',
     alignItems: 'center',
     paddingHorizontal: 14,
     marginBottom: 3,
   },
   fullWidthNameLabel: {
     color: theme.colors.text,
     fontSize: 11,
     fontWeight: '700',
     flexShrink: 1,
   },
   avatarContainerRight: {
    width: 38,
    height: 38,
    borderRadius: tokens.radius.pill,
    marginLeft: tokens.spacing.sm,
    overflow: 'hidden',
    alignSelf: 'flex-start',
    marginTop: tokens.spacing.lg,
    borderWidth: 2,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.text,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  avatarImage: {
    width: 34,
    height: 34,
    borderRadius: tokens.radius.pill,
  },
  avatarPlaceholder: {
    width: 34,
    height: 34,
    borderRadius: tokens.radius.pill,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholderUser: {
    width: 34,
    height: 34,
    borderRadius: tokens.radius.pill,
    backgroundColor: theme.colors.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholderText: {
    color: theme.colors.text,
    fontWeight: '800',
    fontSize: 14,
  },
  messageContent: {
    maxWidth: '92%',
  },
   messageContentFullWidth: {
     maxWidth: '100%',
     minWidth: 0,
     flex: 1,
     flexBasis: 0,
   },
   messageContentFullWidthColumn: {
     width: '100%',
     maxWidth: '100%',
     minWidth: 0,
     alignSelf: 'stretch',
   },
  mediaBubble: {
    padding: plainBubble ? 0 : 4,
    backgroundColor: plainBubble ? 'transparent' : theme.colors.surface,
  },
  // 媒体消息（图片/表情包）用户与角色共用同一组样式：角色也能发表情包。
  mediaBox: {
    alignItems: 'center',
  },
  // 视频气泡：不做本地回放（避免为回放引入播放器依赖），点按交给系统分享面板
  //（其中含视频播放器），因此卡片本身只给出图标/名称与操作提示。
  videoCard: {
    minWidth: 200,
    maxWidth: '100%',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: mediaRadius,
    backgroundColor: theme.colors.surfaceBorder,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.divider,
  },
  videoCardName: {
    color: theme.colors.text,
    fontSize: fonts.scaled(13),
    fontWeight: '600',
    marginTop: 8,
    maxWidth: 220,
  },
  videoCardHint: {
    color: theme.colors.textFaint,
    fontSize: fonts.scaled(10),
    marginTop: 4,
  },
   messageImage: {
     maxWidth: '100%',
     borderRadius: mediaRadius,
     backgroundColor: theme.colors.surfaceBorder,
   },
  mediaName: {
    color: theme.colors.textFaint,
    fontSize: fonts.scaled(10),
    marginTop: 3,
    maxWidth: '100%',
  },
   inlineImageWrap: {
     marginTop: 6,
     maxWidth: '92%',
   },
   inlineImageFullWidth: {
     width: '100%',
     maxWidth: '100%',
   },
  inlineImageBox: {
    borderRadius: tokens.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: tokens.spacing.lg + 2,
    paddingHorizontal: tokens.spacing.lg,
    borderWidth: tokens.border.thin,
  },
  inlineImageLoading: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.divider,
  },
  inlineImageError: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.danger,
  },
  inlineImageHint: {
    color: theme.colors.textFaint,
    fontSize: fonts.scaled(12),
    marginTop: 6,
    textAlign: 'center',
  },
  inlineImageRetry: {
    marginTop: 10,
    backgroundColor: theme.colors.primary,
    borderRadius: tokens.radius.sm,
    paddingHorizontal: tokens.spacing.lg,
    paddingVertical: 7,
  },
  inlineImageRetryText: {
    color: theme.colors.primaryContrast,
    fontSize: fonts.scaled(12),
    fontWeight: '700',
  },
  inlineImage: {
    width: 220,
    height: 300,
    borderRadius: mediaRadius,
    backgroundColor: theme.colors.surface,
  },
  quoteBlock: {
    borderLeftWidth: 3,
    borderRadius: tokens.radius.xs + 2,
    paddingHorizontal: tokens.spacing.sm,
    paddingVertical: 6,
    marginBottom: tokens.spacing.sm,
  },
  quoteBlockUser: {
    borderLeftColor: theme.colors.primarySoft,
    backgroundColor: theme.colors.primaryAlpha(0.12),
  },
  quoteBlockAssistant: {
    borderLeftColor: theme.colors.primary,
    backgroundColor: theme.colors.primaryAlpha(0.1),
  },
  quoteName: { fontSize: 11, fontWeight: '700', marginBottom: 2 },
  quoteNameUser: { color: theme.colors.quoteOnPrimary },
  quoteNameAssistant: { color: theme.colors.primary },
  quoteText: { fontSize: 12, lineHeight: 17 },
  quoteTextUser: { color: theme.colors.quoteOnPrimaryMuted },
  quoteTextAssistant: { color: theme.colors.textMuted },
  quoteBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: tokens.spacing.sm,
    paddingBottom: 6,
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.divider,
    backgroundColor: theme.colors.surfaceAlt,
  },
  quoteBarBody: {
    flex: 1,
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.primary,
    paddingLeft: tokens.spacing.sm,
    marginRight: tokens.spacing.sm,
  },
  quoteBarName: { color: theme.colors.primaryMuted, fontSize: 11, fontWeight: '700' },
  quoteBarText: { color: theme.colors.textFaint, fontSize: 12, marginTop: 2 },
  nameLabel: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
    marginLeft: 2,
  },
  reasoningBox: {
    backgroundColor: theme.colors.primaryAlpha(0.1),
    borderRadius: tokens.radius.sm + 2,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: tokens.spacing.sm,
    alignSelf: 'flex-start',
    maxWidth: '100%',
    borderLeftWidth: 2,
    borderLeftColor: theme.colors.primaryMuted,
  },
  reasoningBoxCollapsed: { paddingVertical: tokens.spacing.xs + 1 },
  reasoningHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: tokens.spacing.xs,
  },
  reasoningHeaderCollapsed: { marginBottom: 0 },
  reasoningLabel: {
    color: theme.colors.primary,
    fontSize: 11,
    fontWeight: '700',
    marginLeft: 4,
    marginRight: 4,
  },
  reasoningText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  messageActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: tokens.spacing.xs,
  },
  messageActionsLeft: {
    justifyContent: 'flex-start',
  },
  messageActionsRight: {
    justifyContent: 'flex-end',
  },
  messageActionButton: {
    paddingHorizontal: 10,
    paddingVertical: tokens.spacing.xs,
    borderRadius: tokens.radius.md,
    backgroundColor: theme.colors.surface,
    marginRight: 6,
    marginTop: tokens.spacing.xs,
    minWidth: 34,
    alignItems: 'center',
    justifyContent: 'center',
    ...tokens.elevation(1, theme),
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
  },
  messageActionButtonOverlay: {
    backgroundColor: theme.colors.surfaceAlpha(0.3),
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
  },
  messageActionText: {
    color: theme.colors.primarySoft,
    fontSize: 12,
    fontWeight: '700',
  },
  messageActionsBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'flex-end',
    padding: tokens.spacing.md,
  },
  messageActionsSheet: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: tokens.radius.md + 2,
    paddingVertical: 6,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    ...tokens.elevation(2, theme),
  },
  markdownCodeScroll: {
    maxWidth: '100%',
  },
  markdownTableScroll: {
    maxWidth: '100%',
  },
  bubble: {
    maxWidth: '95%',
    borderRadius: bubbleRadius,
    paddingHorizontal: bubblePaddingHorizontal,
    paddingVertical: bubblePaddingVertical,
    ...(hasShadow ? tokens.elevation(1, theme) : {}),
    shadowColor: hasShadow ? theme.colors.primary : 'transparent',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: hasShadow ? (theme.id === 'light' ? 0.06 : 0.12) : 0,
    shadowRadius: 6,
  },
  bubbleBounded: {
    maxWidth: '95%',
  },
  bubbleFullWidth: {
    width: '100%',
    maxWidth: '100%',
    minWidth: 0,
    flexShrink: 1,
    alignSelf: 'stretch',
  },
  userBubble: {
    backgroundColor: userBackground,
    borderBottomRightRadius: tailRadius,
    ...(plainBubble ? {} : {
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: theme.id === 'light' ? 0.18 : 0.28,
      shadowRadius: 8,
    }),
  },
  assistantBubble: {
    backgroundColor: assistantBackground,
    borderBottomLeftRadius: tailRadius,
    ...(plainBubble ? {} : {
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: theme.id === 'light' ? 0.04 : 0.08,
      shadowRadius: 5,
    }),
  },
  bubbleMatch: {
    borderWidth: 2,
    borderColor: theme.colors.star,
  },
  bubbleActiveMatch: {
    borderWidth: 2,
    borderColor: theme.colors.star,
  },
  bubbleSelected: {
    borderWidth: 2,
    borderColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  thinkingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 28,
  },
  thinkingText: {
    color: theme.colors.textFaint,
    fontSize: 14,
    lineHeight: 22,
    marginRight: 6,
  },
  thinkingDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    marginLeft: 4,
    backgroundColor: theme.colors.primary,
  },
  panelButton: {
    marginTop: 6,
    borderRadius: tokens.radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: theme.colors.panelButtonBg,
  },
  panelButtonPressed: {
    opacity: 0.75,
  },
  panelButtonText: {
    color: theme.colors.panelButtonText,
    fontSize: 13,
    lineHeight: 18,
  },
  modelLoadBanner: {
    paddingHorizontal: tokens.spacing.lg,
    paddingTop: 6,
    paddingBottom: 2,
  },
  modelLoadText: {
    color: theme.colors.textFaint,
    fontSize: fonts.scaled(11),
    marginBottom: 4,
  },
  modelLoadTrack: {
    height: 4,
    borderRadius: tokens.radius.xs,
    backgroundColor: theme.colors.surfaceAlt,
    overflow: 'hidden',
  },
  modelLoadFill: {
    height: 4,
    borderRadius: tokens.radius.xs,
    backgroundColor: theme.colors.primary,
  },
  errorBubbleBounded: {
     backgroundColor: theme.colors.dangerSurface,
     borderColor: theme.colors.danger,
     borderWidth: tokens.border.thin,
     borderBottomLeftRadius: tokens.radius.tail,
     maxWidth: '92%',
   },
   errorBubbleFullWidth: {
     backgroundColor: theme.colors.dangerSurface,
     borderColor: theme.colors.danger,
     borderWidth: tokens.border.thin,
     borderBottomLeftRadius: tokens.radius.tail,
     maxWidth: '100%',
   },
  errorBadge: {
    color: theme.colors.danger,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  errorSummary: {
    color: theme.colors.dangerTextStrong,
    fontSize: 15,
    lineHeight: 21,
  },
  errorDetail: {
    color: theme.colors.dangerTextSoft,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
  },
  errorActions: {
    marginTop: 10,
    alignItems: 'flex-end',
  },
  copyButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.metrics.buttonRadius,
    backgroundColor: theme.colors.danger,
  },
  copyButtonText: {
    color: theme.colors.primaryContrast,
    fontSize: 12,
    fontWeight: '700',
  },
  messageText: {
    color: userTextColor,
    fontSize: 15,
    lineHeight: 21,
  },
  highlightText: {
    backgroundColor: theme.colors.highlightBg,
    color: theme.colors.highlightText,
    fontWeight: '700',
  },
  attachmentBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 4,
  },
  attachmentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 6,
    maxWidth: 220,
  },
  attachmentThumb: { width: 20, height: 20, borderRadius: tokens.spacing.xs, marginRight: 6 },
  stickerButton: {
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  stickerBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: theme.colors.overlay,
  },
  stickerSheet: {
    backgroundColor: theme.colors.surfaceAlt,
    borderTopLeftRadius: tokens.radius.lg,
    borderTopRightRadius: tokens.radius.lg,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 24,
    maxHeight: '72%',
  },
  stickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  stickerTitle: {
    color: theme.colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  stickerScroll: {
    maxHeight: 360,
  },
  stickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  stickerAddTile: {
    width: 78,
    height: 92,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: tokens.radius.md,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primary,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.1),
  },
  stickerAddText: {
    color: theme.colors.primarySoft,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  stickerTile: {
    width: 78,
    height: 92,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: tokens.radius.md,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  stickerImage: {
    width: 62,
    height: 62,
    borderRadius: tokens.radius.sm,
    backgroundColor: theme.colors.surfaceBorder,
  },
  stickerName: {
    color: theme.colors.textFaint,
    fontSize: 10,
    maxWidth: 66,
    marginTop: 3,
  },
  stickerHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stickerEditText: {
    color: theme.colors.primarySoft,
    fontSize: 13,
    fontWeight: '700',
  },
  stickerHeaderClose: {
    marginLeft: 16,
  },
  stickerTileButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  stickerTileSelected: {
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primary,
  },
  stickerTileDragging: {
    opacity: 0.75,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primary,
  },
  stickerTileDragOver: {
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primarySoft,
  },
  stickerCheck: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: 19,
    height: 19,
    borderRadius: tokens.radius.pill,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stickerCheckOn: {
    backgroundColor: theme.colors.primary,
  },
  stickerEditBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 10,
    borderTopWidth: tokens.border.thin,
    borderTopColor: theme.colors.divider,
  },
  stickerEditHint: {
    flex: 1,
    color: theme.colors.textFaint,
    fontSize: 12,
    marginRight: 12,
  },
  stickerDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: tokens.radius.pill,
    backgroundColor: theme.colors.danger,
  },
  stickerDeleteText: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginLeft: 5,
  },
  stickerNameInput: {
    minHeight: 44,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surface,
    color: theme.colors.text,
    paddingHorizontal: 12,
    fontSize: 15,
  },
  stickerNameActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 14,
  },
  attachmentName: { color: theme.colors.textMuted, fontSize: 12, flexShrink: 1, marginRight: 6, marginLeft: 4 },
  attachButton: { paddingHorizontal: 6, paddingVertical: 6 },
  voiceHoldButtonActive: { backgroundColor: theme.colors.primaryAlpha(0.16), borderRadius: tokens.radius.md },
  voiceRecordingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.sm,
    marginHorizontal: tokens.spacing.sm,
    marginBottom: 4,
    borderRadius: tokens.radius.md,
    backgroundColor: theme.colors.dangerAlpha(0.14),
  },
  voiceRecordingText: { flex: 1, color: theme.colors.text, fontSize: fonts.scaled(13), marginLeft: 8 },
  voiceCancelText: { color: theme.colors.danger, fontSize: fonts.scaled(13), fontWeight: '700', paddingHorizontal: 6 },
  mentionButtonText: {
    color: theme.colors.primarySoft,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
    paddingHorizontal: 4,
  },
  fullScreenButton: { paddingHorizontal: 6, paddingVertical: 6 },
  fullScreenContainer: { flex: 1, backgroundColor: theme.colors.background, paddingTop: 48 },
  fullScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomWidth: tokens.border.thin,
    borderBottomColor: theme.colors.surface,
  },
  fullScreenTitle: { color: theme.colors.text, fontSize: 17, fontWeight: '800' },
  fullScreenInput: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 16,
    lineHeight: 23,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
  },
  fullScreenSend: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginBottom: 20,
    backgroundColor: theme.colors.primary,
    borderRadius: tokens.metrics.buttonRadius,
    paddingVertical: 12,
  },
  fullScreenSendText: { color: theme.colors.text, fontSize: 15, fontWeight: '700', marginLeft: 6 },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm + 2,
    paddingBottom: tokens.spacing.md,
    borderTopWidth: tokens.border.thin,
    borderTopColor: theme.colors.divider,
    backgroundColor: theme.colors.background,
  },
  inputBarSurface: {
    backgroundColor: theme.colors.background,
  },
  inputBarOverlay: {
    backgroundColor: hexToRgba(theme.colors.background, 0.26),
  },
  input: {
    flex: 1,
    minHeight: 42,
    maxHeight: 110,
    borderRadius: tokens.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    color: theme.colors.text,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
  },
  inputFocused: {
    borderColor: theme.colors.primaryMuted,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  inputOverlay: {
    backgroundColor: theme.colors.surfaceAlpha(0.28),
    borderColor: hexToRgba(theme.colors.text, 0.22),
  },
  sendButton: {
    marginLeft: tokens.spacing.sm,
    width: 44,
    height: 44,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
    ...tokens.elevation(2, theme),
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: theme.id === 'light' ? 0.28 : 0.4,
    shadowRadius: 7,
  },
  sendButtonDisabled: {
    opacity: tokens.opacity.disabled,
    elevation: 0,
    shadowOpacity: 0,
  },
  stopButton: {
    backgroundColor: theme.colors.danger,
    shadowColor: theme.colors.danger,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: theme.id === 'light' ? 0.28 : 0.4,
    shadowRadius: 7,
  },
});
};
