// 本地模型面板共享样式（Phase 2 拆分）：壳与各 Section 用同一套 createPanelStyles，
// 避免样式在各文件间复制漂移。

import { Platform, StyleSheet } from 'react-native';

export function createPanelStyles(theme, fonts, tokens) {
  return StyleSheet.create({
    backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: theme.colors.overlay },
    sheet: { maxHeight: '90%', backgroundColor: theme.colors.surfaceAlt, borderTopLeftRadius: 18, borderTopRightRadius: 18, padding: 18 },
    // 模型中心容器 = 全屏（设计书 §3）：运行卡 + 下载卡 + 模型卡列表需要整屏；
    // 顶部长按区留 44（与工作区单屏同口径）。backdrop/sheet 仍归参数/搜索等弹层用。
    centerScreen: {
      flex: 1,
      backgroundColor: theme.colors.background,
      paddingTop: 44,
      paddingHorizontal: 18,
    },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
    title: { color: theme.colors.text, fontSize: fonts.scaled(18), fontWeight: '800' },
    content: { paddingBottom: 18 },
    // 分段 = 独立胶囊组（v5 设计稿）：激活胶囊反色实底、其余描边胶囊；
    // 不再是「外框 + 内高亮」的 segmented 控件（设计稿里就没有外框）。
    tabRow: { flexDirection: 'row', columnGap: 6, marginBottom: 10 },
    subTabRow: { flexDirection: 'row', columnGap: 6, marginBottom: 12 },
    tabItem: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 6,
      borderRadius: tokens.radius.pill,
      borderWidth: 1,
      borderColor: theme.colors.surfaceBorder,
    },
    // 反色实底：底用正文色、字用背景色——深浅主题下都保持高对比。
    tabItemActive: { backgroundColor: theme.colors.text, borderColor: theme.colors.text },
    tabText: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), fontWeight: '600' },
    tabTextActive: { color: theme.colors.background, fontWeight: '700' },
    hint: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18), marginBottom: 10 },
    // 面板标题行右侧：教学入口 + 关闭
    headerActions: { flexDirection: 'row', alignItems: 'center', columnGap: 10 },
    status: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), marginBottom: 10 },
    logsButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', marginTop: 12 },
    logsButtonText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    activeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, paddingHorizontal: 12, paddingVertical: 10 },
    activeText: { flex: 1, color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700', marginRight: 8 },
    mediaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, paddingHorizontal: 12, paddingVertical: 10, marginTop: 8 },
    mediaInfo: { flex: 1, marginRight: 8 },
    mediaTitle: { color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700' },
    mediaHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), lineHeight: fonts.scaled(16), marginTop: 2 },
    apiPortRow: { flexDirection: 'row', alignItems: 'center' },
    apiPortInput: { flex: 1, marginLeft: 10 },
    apiSwitchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, paddingHorizontal: 12, paddingVertical: 8, marginTop: 10 },
    apiAddressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 6,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: tokens.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.surfaceBorder,
      backgroundColor: theme.colors.surface,
    },
    apiAddress: { flex: 1, color: theme.colors.text, fontSize: fonts.scaled(13), fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
    apiCopyChip: { flexDirection: 'row', alignItems: 'center', marginLeft: 10 },
    apiCopyText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    apiAddressHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), lineHeight: fonts.scaled(16), marginTop: 6 },
    item: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, padding: 10, marginBottom: 8 },
    itemActive: { borderColor: theme.colors.primary },
    itemHeader: { flexDirection: 'row', alignItems: 'center' },
    itemInfo: { flex: 1, marginRight: 8 },
    itemName: { color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700' },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: 6 },
    chip: { color: theme.colors.textMuted, fontSize: fonts.scaled(11), marginRight: 10, marginBottom: 4 },
    tierChip: { fontSize: fonts.scaled(11), fontWeight: '800', marginBottom: 4 },
    itemActions: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
    selectButton: { borderRadius: tokens.radius.pill, borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.5), paddingHorizontal: 14, paddingVertical: 6, marginRight: 10 },
    // 「设为当前」是主操作 = 实底反衬（成品小样）；「下载」保持描边，层级拉开。
    selectButtonPrimary: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
    selectButtonPrimaryText: { color: theme.colors.primaryContrast },
    loadButtonBusy: { opacity: 0.75 },
    loadProgressRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
    loadProgressBar: { flex: 1, height: 4, borderRadius: 2, backgroundColor: theme.colors.surfaceBorder, overflow: 'hidden' },
    loadProgressFill: { height: '100%', borderRadius: 2, backgroundColor: theme.colors.primary },
    loadProgressText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(11), fontWeight: '700', marginLeft: 8, minWidth: 36, textAlign: 'right' },
    selectButtonActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primaryAlpha(0.18) },
    selectButtonText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700' },
    iconButton: { flexDirection: 'row', alignItems: 'center', marginRight: 14 },
    // 删除按钮是 itemActions 行的最后一个元素：marginRight 归零，danger 色（变体）。
    deleteIconButton: { marginRight: 0 },
    deleteIconButtonText: { color: theme.colors.danger || theme.colors.textFaint },
    iconButtonText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    itemBytes: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), fontWeight: '700', marginLeft: 8 },
    empty: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18), marginBottom: 8 },
    sourceRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
    sourceChip: { borderRadius: tokens.radius.pill, borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.45), backgroundColor: theme.colors.primaryAlpha(0.12), paddingHorizontal: 14, paddingVertical: 8, marginRight: 8, marginBottom: 8 },
    sourceChipActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primaryAlpha(0.22) },
    sourceChipText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(13), fontWeight: '700' },
    sourceChipTextActive: { color: theme.colors.primary },
    label: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), fontWeight: '700', marginTop: 10, marginBottom: 5 },
    labelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10, marginBottom: 5 },
    labelInline: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), fontWeight: '700' },
    searchModelButton: { flexDirection: 'row', alignItems: 'center' },
    searchModelText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    summaryCard: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, padding: 12, marginTop: 10 },
    summaryName: { color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700' },
    summaryRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: 8 },
    summaryChip: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), marginRight: 12, marginBottom: 4 },
    summaryTier: { fontSize: fonts.scaled(12), fontWeight: '800', marginBottom: 4 },
    summaryHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), lineHeight: fonts.scaled(16), marginTop: 8 },
    input: { minHeight: 42, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, backgroundColor: theme.colors.surface, color: theme.colors.text, paddingHorizontal: 12, paddingVertical: 9 },
    loading: { marginVertical: 10 },
    primary: { backgroundColor: theme.colors.primary, borderRadius: tokens.radius.md, paddingVertical: 12, alignItems: 'center', marginTop: 16 },
    primaryText: { color: theme.colors.primaryContrast, fontSize: fonts.scaled(14), fontWeight: '700' },
    secondary: { backgroundColor: theme.colors.primaryAlpha(0.12), borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.4), borderRadius: tokens.radius.md, paddingVertical: 12, alignItems: 'center', marginTop: 10 },
    secondaryText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(14), fontWeight: '700' },
    downloadProgressWrap: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
    downloadProgressBar: { flex: 1, height: 12, borderRadius: 6, backgroundColor: theme.colors.surfaceBorder, overflow: 'hidden' },
    downloadProgressFill: { height: '100%', borderRadius: 6, backgroundColor: theme.colors.primary },
    downloadProgressText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(11), fontWeight: '700', marginLeft: 10, minWidth: 96, textAlign: 'right' },
    downloadButtons: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
    downloadMainButton: { flex: 1 },
    downloadCancelButton: { marginLeft: 10, marginTop: 16, paddingHorizontal: 14, paddingVertical: 12, borderRadius: tokens.radius.md, borderWidth: 1, borderColor: theme.colors.dangerSoft },
    downloadCancelText: { color: theme.colors.dangerSoft, fontSize: fonts.scaled(13), fontWeight: '700' },
    paramField: { marginBottom: 4 },
  // 「高级」折叠开关（v5 Stage C §6）：预设 + contextSize 之外的技术字段默认收起。
  advancedToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  advancedToggleText: { color: theme.colors.primary, fontSize: fonts.scaled(13), fontWeight: '700' },
    // U7 完整版：字段标签行（左侧名称 + 右侧「恢复默认」）+ 越界红框与行内错误
    paramLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    resetText: { color: theme.colors.primary, fontSize: fonts.scaled(12), fontWeight: '600' },
    inputError: { borderColor: theme.colors.danger || theme.colors.primary, borderWidth: 2 },
    fieldError: {
      color: theme.colors.danger || theme.colors.textMuted,
      fontSize: fonts.scaled(11),
      marginTop: 4,
    },
    resetAll: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', marginTop: 12, marginBottom: 2 },
    resetAllText: { color: theme.colors.primary, fontSize: fonts.scaled(12), fontWeight: '600', marginLeft: 5 },
    engineCard: { borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.45), borderRadius: tokens.radius.md, padding: 12, marginBottom: 8, backgroundColor: theme.colors.primaryAlpha(0.08) },
    // 运行状态卡（v5 Stage C，预览对齐）
    // 运行状态卡（v5 设计稿）：就绪 = 绿（success 语义色）、加载中 = 品牌色、失败 = 红。
    runCard: { borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, padding: 12, marginBottom: 8, backgroundColor: theme.colors.surface },
    runCardReady: { borderColor: theme.colors.success, backgroundColor: theme.colors.successSurface },
    runCardLoading: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primaryAlpha(0.1) },
    runCardError: { borderColor: theme.colors.danger, backgroundColor: theme.colors.dangerSurface },
    runHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    runNameWrap: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 8 },
    runDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: theme.colors.textFaint, marginRight: 7 },
    runDotReady: { backgroundColor: theme.colors.success },
    runDotLoading: { backgroundColor: theme.colors.primary },
    runDotError: { backgroundColor: theme.colors.danger },
    runName: { flex: 1, color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700' },
    runBadge: { color: theme.colors.textMuted, fontSize: fonts.scaled(10), fontWeight: '700', borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.pill, paddingHorizontal: 8, paddingVertical: 1 },
    runBadgeReady: { color: theme.colors.success, borderColor: theme.colors.success },
    runMeta: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), marginTop: 5 },
    runActions: { flexDirection: 'row', alignItems: 'center', marginTop: 9, columnGap: 8 },
    runButton: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.sm, paddingHorizontal: 10, paddingVertical: 4 },
    runButtonText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(11), fontWeight: '700', marginLeft: 4 },
    runButtonDanger: { color: theme.colors.dangerSoft },
    // 模型卡状态徽章 + 单行摘要
    cardBadge: { color: theme.colors.textFaint, fontSize: fonts.scaled(10), fontWeight: '700', borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.pill, paddingHorizontal: 8, paddingVertical: 1 },
    cardBadgeActive: { color: theme.colors.primary, borderColor: theme.colors.primary },
    cardBadgeInstalled: { color: theme.colors.textMuted, borderColor: theme.colors.surfaceBorder },
    cardBadgeMissing: { color: theme.colors.textFaint, borderColor: theme.colors.surfaceBorder, borderStyle: 'dashed' },
    cardSummary: { fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', color: theme.colors.textFaint, fontSize: fonts.scaled(11), marginTop: 6 },
    cardMissing: { opacity: 0.62 },
    // 下载任务卡（v5 Stage B/C）：模型库页顶部，队列任务可多张。
    downloadTaskWrap: { marginBottom: 8 },
    downloadTaskTitle: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '800', marginBottom: 6 },
    downloadTaskCard: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.45), borderRadius: tokens.radius.md, padding: 10, marginBottom: 8 },
    downloadTaskHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    downloadTaskName: { flex: 1, color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700', marginRight: 8 },
    downloadTaskCount: { color: theme.colors.primarySoft, fontSize: fonts.scaled(10), fontWeight: '700' },
    downloadTaskMeta: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), marginTop: 6 },
    downloadTaskFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6 },
    downloadTaskFooterMeta: { flex: 1, color: theme.colors.textFaint, fontSize: fonts.scaled(10), marginRight: 8 },
    downloadProgressRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
    // 卡片操作行的「更多」菜单
    cardMenuBackdrop: { flex: 1, backgroundColor: theme.colors.overlay, justifyContent: 'flex-end' },
    cardMenuSheet: { backgroundColor: theme.colors.surfaceAlt, borderTopLeftRadius: 18, borderTopRightRadius: 18, paddingVertical: 8, paddingHorizontal: 8 },
    cardMenuRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, paddingHorizontal: 12 },
    cardMenuText: { color: theme.colors.textMuted, fontSize: fonts.scaled(14), marginLeft: 10 },
    cardMenuDanger: { color: theme.colors.danger },
    cardMenuIcon: { width: 18 },
  });
}
