// 本地模型面板共享样式（Phase 2 拆分）：壳与各 Section 用同一套 createPanelStyles，
// 避免样式在各文件间复制漂移。

import { Platform, StyleSheet } from 'react-native';

export function createPanelStyles(theme, fonts, tokens) {
  return StyleSheet.create({
    backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: theme.colors.overlay },
    sheet: { maxHeight: '90%', backgroundColor: theme.colors.surfaceAlt, borderTopLeftRadius: 18, borderTopRightRadius: 18, padding: 18 },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
    title: { color: theme.colors.text, fontSize: fonts.scaled(18), fontWeight: '800' },
    content: { paddingBottom: 18 },
    tabRow: {
      flexDirection: 'row',
      backgroundColor: theme.colors.surface,
      borderRadius: tokens.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.surfaceBorder,
      padding: 3,
      marginBottom: 10,
    },
    subTabRow: {
      flexDirection: 'row',
      backgroundColor: theme.colors.surface,
      borderRadius: tokens.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.surfaceBorder,
      padding: 3,
      marginBottom: 12,
    },
    tabItem: { flex: 1, alignItems: 'center', paddingVertical: 7, borderRadius: tokens.radius.sm },
    tabItemActive: { backgroundColor: theme.colors.primaryAlpha(0.2) },
    tabText: { color: theme.colors.textMuted, fontSize: fonts.scaled(13), fontWeight: '700' },
    tabTextActive: { color: theme.colors.primary },
    hint: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18), marginBottom: 10 },
    status: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), marginBottom: 10 },
    logsButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', marginTop: 12 },
    logsButtonText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    activeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, paddingHorizontal: 12, paddingVertical: 10 },
    activeText: { flex: 1, color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700', marginRight: 8 },
    mediaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, paddingHorizontal: 12, paddingVertical: 10, marginTop: 8 },
    mediaInfo: { flex: 1, marginRight: 8 },
    mediaTitle: { color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700' },
    mediaHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), lineHeight: fonts.scaled(16), marginTop: 2 },
    apiPortRow: { flexDirection: 'row', alignItems: 'center' },
    apiPortInput: { flex: 1, marginLeft: 10 },
    apiSwitchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, paddingHorizontal: 12, paddingVertical: 8, marginTop: 10 },
    apiAddressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 6,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: tokens.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.surfaceBorder,
      backgroundColor: theme.colors.surface,
    },
    apiAddress: { flex: 1, color: theme.colors.text, fontSize: fonts.scaled(13), fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
    apiCopyChip: { flexDirection: 'row', alignItems: 'center', marginLeft: 10 },
    apiCopyText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    apiAddressHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), lineHeight: fonts.scaled(16), marginTop: 6 },
    item: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, padding: 10, marginBottom: 8 },
    itemActive: { borderColor: theme.colors.primary },
    itemHeader: { flexDirection: 'row', alignItems: 'center' },
    itemInfo: { flex: 1, marginRight: 8 },
    itemName: { color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700' },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: 6 },
    chip: { color: theme.colors.textMuted, fontSize: fonts.scaled(11), marginRight: 10, marginBottom: 4 },
    tierChip: { fontSize: fonts.scaled(11), fontWeight: '800', marginBottom: 4 },
    itemActions: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
    selectButton: { borderRadius: tokens.radius.pill, borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.5), paddingHorizontal: 14, paddingVertical: 6, marginRight: 10 },
    loadButtonBusy: { opacity: 0.75 },
    loadProgressRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
    loadProgressBar: { flex: 1, height: 4, borderRadius: 2, backgroundColor: theme.colors.surfaceBorder, overflow: 'hidden' },
    loadProgressFill: { height: '100%', borderRadius: 2, backgroundColor: theme.colors.primary },
    loadProgressText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(11), fontWeight: '700', marginLeft: 8, minWidth: 36, textAlign: 'right' },
    selectButtonActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primaryAlpha(0.18) },
    selectButtonText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700' },
    iconButton: { flexDirection: 'row', alignItems: 'center', marginRight: 14 },
    iconButtonText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    itemBytes: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), fontWeight: '700', marginLeft: 8 },
    empty: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18), marginBottom: 8 },
    sourceRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
    sourceChip: { borderRadius: tokens.radius.pill, borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.45), backgroundColor: theme.colors.primaryAlpha(0.12), paddingHorizontal: 14, paddingVertical: 8, marginRight: 8, marginBottom: 8 },
    sourceChipActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primaryAlpha(0.22) },
    sourceChipText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(13), fontWeight: '700' },
    sourceChipTextActive: { color: theme.colors.primary },
    label: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), fontWeight: '700', marginTop: 10, marginBottom: 5 },
    labelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10, marginBottom: 5 },
    labelInline: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), fontWeight: '700' },
    searchModelButton: { flexDirection: 'row', alignItems: 'center' },
    searchModelText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(12), fontWeight: '700', marginLeft: 4 },
    summaryCard: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, padding: 12, marginTop: 10 },
    summaryName: { color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700' },
    summaryRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: 8 },
    summaryChip: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), marginRight: 12, marginBottom: 4 },
    summaryTier: { fontSize: fonts.scaled(12), fontWeight: '800', marginBottom: 4 },
    summaryHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(11), lineHeight: fonts.scaled(16), marginTop: 8 },
    input: { minHeight: 42, borderWidth: 1, borderColor: theme.colors.surfaceBorder, borderRadius: tokens.radius.md, backgroundColor: theme.colors.surface, color: theme.colors.text, paddingHorizontal: 12, paddingVertical: 9 },
    loading: { marginVertical: 10 },
    primary: { backgroundColor: theme.colors.primary, borderRadius: tokens.radius.md, paddingVertical: 12, alignItems: 'center', marginTop: 16 },
    primaryText: { color: theme.colors.primaryContrast, fontSize: fonts.scaled(14), fontWeight: '700' },
    secondary: { backgroundColor: theme.colors.primaryAlpha(0.12), borderWidth: 1, borderColor: theme.colors.primaryMutedAlpha(0.4), borderRadius: tokens.radius.md, paddingVertical: 12, alignItems: 'center', marginTop: 10 },
    secondaryText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(14), fontWeight: '700' },
    downloadProgressWrap: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
    downloadProgressBar: { flex: 1, height: 12, borderRadius: 6, backgroundColor: theme.colors.surfaceBorder, overflow: 'hidden' },
    downloadProgressFill: { height: '100%', borderRadius: 6, backgroundColor: theme.colors.primary },
    downloadProgressText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(11), fontWeight: '700', marginLeft: 10, minWidth: 96, textAlign: 'right' },
    downloadButtons: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
    downloadMainButton: { flex: 1 },
    downloadCancelButton: { marginLeft: 10, marginTop: 16, paddingHorizontal: 14, paddingVertical: 12, borderRadius: tokens.radius.md, borderWidth: 1, borderColor: theme.colors.dangerSoft },
    downloadCancelText: { color: theme.colors.dangerSoft, fontSize: fonts.scaled(13), fontWeight: '700' },
    paramField: { marginBottom: 4 },
  });
}
