export const IMAGE_PROVIDERS = [
  {
    id: 'z-image',
    label: 'Z-Image',
    baseUrl: 'https://api.z-image.ai/v1/images/generations',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    modelField: 'model',
    promptField: 'prompt',
    negativePromptField: 'negative_prompt',
    params: { size: 'size', width: 'width', height: 'height', steps: 'num_inference_steps', guidance: 'guidance_scale', seed: 'seed' },
    t2i: {
      template: {
        model: '{model}',
        prompt: '{prompt}',
        n: 1,
        response_format: 'url',
      },
    },
    i2i: {
      mode: 'base64',
      imageField: 'image',
      template: {
        model: '{model}',
        prompt: '{prompt}',
        image: '{image}',
        strength: '{strength}',
        response_format: 'url',
      },
    },
    response: { path: 'data', urlField: 'url', base64Field: 'b64_json' },
    timeoutMs: 60000,
    retries: 1,
    extraDefaults: { response_format: 'url' },
  },
  {
    id: 'wan-image',
    label: 'Wan Image',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    modelField: 'model',
    promptField: 'input.prompt',
    negativePromptField: 'input.negative_prompt',
    params: { size: 'parameters.size', steps: 'parameters.n', seed: 'parameters.seed' },
    t2i: {
      template: {
        model: '{model}',
        input: { prompt: '{prompt}' },
        parameters: { n: 1, size: '1024*1024' },
      },
    },
    i2i: {
      mode: 'url',
      imageField: 'input.image_url',
      template: {
        model: '{model}',
        input: { prompt: '{prompt}', image_url: '{image}' },
        parameters: { n: 1 },
      },
    },
    response: { path: 'output.results', urlField: 'url', base64Field: 'b64_image' },
    timeoutMs: 90000,
    retries: 1,
    extraDefaults: {},
  },
  {
    id: 'qwen-image',
    label: 'Qwen Image',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    modelField: 'model',
    promptField: 'input.messages',
    negativePromptField: '',
    params: { size: 'parameters.size', steps: 'parameters.steps', seed: 'parameters.seed' },
    t2i: {
      template: {
        model: '{model}',
        input: { messages: [{ role: 'user', content: [{ text: '{prompt}' }] }] },
        parameters: { size: '1024*1024' },
      },
    },
    i2i: {
      mode: 'url',
      imageField: '',
      template: {
        model: '{model}',
        input: {
          messages: [{
            role: 'user',
            content: [{ image: '{image}' }, { text: '{prompt}' }],
          }],
        },
      },
    },
    response: { path: 'output.choices', urlField: 'message.content.0.image', base64Field: '' },
    timeoutMs: 90000,
    retries: 1,
    extraDefaults: {},
  },
  {
    id: 'flux2-klein-4b',
    label: 'FLUX.2-klein-4B',
    baseUrl: 'https://api.replicate.com/v1/predictions',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    modelField: 'model',
    promptField: 'input.prompt',
    negativePromptField: 'input.negative_prompt',
    params: { size: 'input.aspect_ratio', steps: 'input.num_inference_steps', guidance: 'input.guidance', seed: 'input.seed' },
    t2i: {
      template: {
        model: '{model}',
        input: { prompt: '{prompt}', output_format: 'png' },
      },
    },
    i2i: {
      mode: 'base64',
      imageField: 'input.image',
      template: {
        model: '{model}',
        input: { prompt: '{prompt}', image: '{image}', output_format: 'png' },
      },
    },
    response: { path: 'output', urlField: '0', base64Field: '' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: {},
  },
  {
    id: 'glm-image',
    label: 'GLM-Image',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4/images/generations',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    modelField: 'model',
    promptField: 'prompt',
    negativePromptField: '',
    params: { size: 'size', seed: 'seed' },
    t2i: {
      template: { model: '{model}', prompt: '{prompt}' },
    },
    i2i: {
      mode: 'url',
      imageField: 'image',
      template: { model: '{model}', prompt: '{prompt}', image: '{image}' },
    },
    response: { path: 'data', urlField: 'url', base64Field: 'b64_json' },
    timeoutMs: 60000,
    retries: 1,
    extraDefaults: {},
  },
  {
    id: 'openai-compatible',
    label: 'OpenAI 兼容',
    baseUrl: '',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    modelField: 'model',
    promptField: 'prompt',
    negativePromptField: '',
    params: { size: 'size', seed: 'seed' },
    t2i: {
      template: { model: '{model}', prompt: '{prompt}', n: 1, response_format: 'url' },
    },
    i2i: {
      mode: 'url',
      imageField: 'image',
      template: { model: '{model}', prompt: '{prompt}', image: '{image}', n: 1, response_format: 'url' },
    },
    response: { path: 'data', urlField: 'url', base64Field: 'b64_json' },
    timeoutMs: 90000,
    retries: 1,
    extraDefaults: { response_format: 'url' },
    custom: true,
  },
];

export function getImageProvider(id) {
  return IMAGE_PROVIDERS.find(provider => provider.id === id) || IMAGE_PROVIDERS[0];
}
