export const IMAGE_PROVIDERS = [
  {
    id: 'google-ai-studio',
    label: 'Google AI Studio',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent',
    method: 'POST',
    requestFormat: 'json',
    auth: { type: 'header', keyName: 'x-goog-api-key', prefix: '' },
    headers: { 'Content-Type': 'application/json' },
    modelField: '',
    defaultModel: 'gemini-2.0-flash-preview-image-generation',
    listModelsPath: '/v1beta/models',
    promptField: '',
    params: {},
    t2i: {
      template: {
        contents: [{ role: 'user', parts: [{ text: '{prompt}' }] }],
        generationConfig: { responseModalities: ['TEXT', 'IMAGE'] },
      },
    },
    i2i: {
      stripImagePrefix: true,
      template: {
        contents: [{
          role: 'user',
          parts: [
            { inlineData: { mimeType: '{mime}', data: '{image}' } },
            { text: '{prompt}' },
          ],
        }],
        generationConfig: { responseModalities: ['TEXT', 'IMAGE'] },
      },
    },
    response: { path: 'candidates.0.content.parts', base64Field: 'inlineData.data' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: {},
    keyHint: '以 AIza 开头；需在 Google Cloud Console 设置 Referrer 限制，否则可能 403。',
    cors: 'blocked',
    corsNote: '默认不支持浏览器跨域直连，纯网页环境可能需自建代理。',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1/images',
    method: 'POST',
    requestFormat: 'json',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    headers: { 'Content-Type': 'application/json', 'X-OpenRouter-Title': 'EasyChat2' },
    modelField: 'model',
    defaultModel: 'google/gemini-2.5-flash-image-preview',
    listModelsPath: '/api/v1/images/models',
    promptField: 'prompt',
    params: { size: 'size' },
    t2i: {
      template: { model: '{model}', prompt: '{prompt}' },
    },
    i2i: {
      stripImagePrefix: false,
      template: {
        model: '{model}',
        prompt: '{prompt}',
        input_references: [{ type: 'image_url', image_url: { url: '{image}' } }],
      },
    },
    response: { path: 'data', urlField: 'url', base64Field: 'b64_json' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: {},
    keyHint: '以 sk-or- 开头；建议在 OpenRouter 仪表盘设置用量上限。',
    cors: 'ok',
    corsNote: '支持浏览器跨域直连。',
  },
  {
    id: 'stability-ai',
    label: 'Stability AI',
    baseUrl: 'https://api.stability.ai/v2beta/stable-image/generate/ultra',
    method: 'POST',
    requestFormat: 'multipart',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    headers: { Accept: 'application/json' },
    modelField: '',
    defaultModel: '',
    listModelsPath: '',
    promptField: 'prompt',
    params: {},
    t2i: {
      template: { prompt: '{prompt}', output_format: 'png' },
    },
    response: { path: 'image', base64Field: '' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: {},
    keyHint: '以 sk- 开头；不同生成端点参数不同。',
    cors: 'ok',
    corsNote: '官方声明支持浏览器跨域直连。',
  },
  {
    id: 'gitee-ai',
    label: 'ai.gitee 模力方舟',
    baseUrl: 'https://ai.gitee.com/v1/images/generations',
    method: 'POST',
    requestFormat: 'json',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    headers: { 'Content-Type': 'application/json' },
    modelField: 'model',
    defaultModel: 'z-image-turbo',
    listModelsPath: '/v1/models',
    promptField: 'prompt',
    negativePromptField: 'negative_prompt',
    params: { steps: 'num_inference_steps', guidance: 'guidance_scale', seed: 'seed' },
    t2i: {
      template: {
        prompt: '{prompt}',
        model: '{model}',
        num_images_per_prompt: 1,
        negative_prompt: '',
        num_inference_steps: 9,
        seed: 0,
        guidance_scale: 1,
        response_format: 'b64_json',
      },
    },
    i2i: {
      mode: 'base64',
      stripImagePrefix: true,
      imageField: 'control_image',
      template: {
        prompt: '{prompt}',
        model: '{model}',
        num_images_per_prompt: 1,
        negative_prompt: '',
        num_inference_steps: 9,
        seed: 0,
        guidance_scale: 1,
        response_format: 'b64_json',
        control_image: '{image}',
        control_mode: 'HED',
        control_context_scale: 0.75,
        image_scale: 1,
      },
    },
    response: { path: 'data', urlField: 'url', base64Field: 'b64_json' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: { response_format: 'b64_json' },
    keyHint: '30-60 位无前缀字母数字字符串；建议使用临时令牌。',
    cors: 'warn',
    corsNote: '技术上可直连，官方建议用后端代理。',
  },
  {
    id: 'agnes-ai',
    label: 'Agnes AI',
    baseUrl: 'https://apihub.agnes-ai.com/v1/images/generations',
    method: 'POST',
    requestFormat: 'json',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    headers: { 'Content-Type': 'application/json' },
    modelField: 'model',
    defaultModel: 'agnes-image-2.0-flash',
    listModelsPath: '/v1/models',
    promptField: 'prompt',
    params: {},
    t2i: {
      template: { model: '{model}', prompt: '{prompt}' },
    },
    i2i: {
      stripImagePrefix: true,
      template: { model: '{model}', prompt: '{prompt}', image: '{image}' },
    },
    response: { path: 'data', urlField: 'url', base64Field: 'b64_json' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: {},
    keyHint: 'Bearer Token 格式；官方建议使用临时 Key 或设置用量限制。',
    cors: 'ok',
    corsNote: '支持浏览器跨域直连。',
  },
  {
    id: 'openai-relay',
    label: 'OpenAI 兼容中转站',
    baseUrl: '',
    method: 'POST',
    requestFormat: 'json',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    headers: { 'Content-Type': 'application/json' },
    modelField: 'model',
    defaultModel: '',
    listModelsPath: '/v1/models',
    promptField: 'prompt',
    params: { size: 'size', steps: 'steps', seed: 'seed' },
    t2i: {
      template: { model: '{model}', prompt: '{prompt}', n: 1, response_format: 'b64_json' },
    },
    i2i: {
      stripImagePrefix: true,
      template: { model: '{model}', prompt: '{prompt}', image: '{image}', n: 1, response_format: 'b64_json' },
    },
    response: { path: 'data', urlField: 'url', base64Field: 'b64_json' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: { response_format: 'b64_json' },
    keyHint: '由中转站决定；不确定时先用「检测」验证连通性。',
    cors: 'unknown',
    corsNote: '取决于中转站配置，需用「检测」确认能否浏览器直连。',
    custom: true,
  },
  {
    id: 'novelai',
    label: 'NovelAI',
    baseUrl: 'https://image.novelai.net/ai/generate-image',
    method: 'POST',
    requestFormat: 'json',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    headers: { 'Content-Type': 'application/json' },
    modelField: 'model',
    defaultModel: 'nai-diffusion-3',
    listModelsPath: '',
    promptField: 'input',
    negativePromptField: 'negative_prompt',
    params: { steps: 'parameters.steps', guidance: 'parameters.scale', seed: 'parameters.seed' },
    sizeSplit: { width: 'parameters.width', height: 'parameters.height' },
    t2i: {
      template: {
        input: '{prompt}',
        model: 'nai-diffusion-3',
        action: 'generate',
        parameters: {
          width: 832,
          height: 1216,
          scale: 5,
          sampler: 'k_euler',
          steps: 28,
          n_samples: 1,
          ucPreset: 0,
          qualityToggle: true,
        },
      },
    },
    i2i: {
      mode: 'base64',
      stripImagePrefix: true,
      imageField: 'parameters.image',
      template: {
        input: '{prompt}',
        model: 'nai-diffusion-3',
        action: 'img2img',
        parameters: {
          image: '{image}',
          strength: 0.7,
          width: 832,
          height: 1216,
          steps: 28,
        },
      },
    },
    response: { mode: 'binary', path: 'images.0', urlField: '', base64Field: '' },
    timeoutMs: 120000,
    retries: 1,
    extraDefaults: {},
    keyHint: 'NovelAI 订阅密钥。',
    cors: 'unknown',
    corsNote: '未公开声明，需自行验证。',
  },
];

export function getImageProvider(id) {
  return IMAGE_PROVIDERS.find(provider => provider.id === id) || IMAGE_PROVIDERS[0];
}

export function isKnownImageProvider(id) {
  return IMAGE_PROVIDERS.some(provider => provider.id === id);
}
