// 设置页样式工厂。从 src/SettingsScreen.js 原样外提（无行为变化），
// 供主屏幕与 settings/ 下的子组件（如 SamplingCard）共用。

import { StyleSheet } from 'react-native';

export const createSettingsStyles = (theme, fonts, tokens) => StyleSheet.create({
  flex: { flex: 1, backgroundColor: theme.colors.background },
  container: { flex: 1, backgroundColor: theme.colors.background, paddingHorizontal: tokens.spacing.lg, paddingTop: tokens.spacing.sm },
  scrollContent: { paddingBottom: 80 },

  pageHeader: { marginTop: 4, marginBottom: 14 },
  title: { color: theme.colors.text, fontSize: fonts.scaled(24), fontWeight: '800', marginBottom: 6 },
  hint: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), marginTop: 6, lineHeight: fonts.scaled(18) },

  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center' },
  cardTitle: { color: theme.colors.text, fontSize: fonts.scaled(15), fontWeight: '800', marginLeft: 8 },
  collapseSummary: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), marginRight: 6 },
  configSelect: { marginTop: 6 },
  providerEditor: {
    marginTop: tokens.spacing.sm,
    paddingTop: tokens.spacing.sm,
    borderTopWidth: tokens.border.thin,
    borderTopColor: theme.colors.divider,
  },
  providerEditorTitle: { color: theme.colors.text, fontSize: fonts.scaled(13), fontWeight: '700', marginTop: tokens.spacing.xs },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  topicButtonSpaced: { marginRight: 8 },
  appearanceRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
  themeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.pill,
    borderWidth: tokens.border.thin * 1.5,
    borderColor: theme.colors.surfaceBorder,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.xs + 2,
    marginRight: tokens.spacing.sm,
    marginBottom: tokens.spacing.sm,
  },
  themeSwatch: {
    width: 20,
    height: 20,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: tokens.spacing.xs + 2,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    overflow: 'hidden',
  },
  themeSwatchDot: { width: 12, height: 12, borderRadius: tokens.radius.pill },
  themeChipText: { color: theme.colors.textMuted, fontSize: fonts.scaled(13), fontWeight: '600' },
  fontRow: { flexDirection: 'row', flexWrap: 'wrap' },
  fontChip: {
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.pill,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.xs + 2,
    marginRight: tokens.spacing.sm,
    marginBottom: tokens.spacing.sm,
  },
  fontChipActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  fontChipText: { color: theme.colors.textMuted, fontSize: fonts.scaled(13) },
  fontChipTextActive: { color: theme.colors.primaryContrast, fontWeight: '700' },
  pillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderWidth: 1,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
  },
  pillButtonText: { color: theme.colors.primarySoft, fontWeight: '700', fontSize: fonts.scaled(13), marginLeft: 4 },

  label: { color: theme.colors.text, marginTop: 14, marginBottom: 6, fontWeight: '700', fontSize: fonts.scaled(13) },
  multilineInput: { minHeight: 100, paddingTop: 12 },
  modelRow: { flexDirection: 'row', alignItems: 'center' },
  modelInput: { flex: 1, minHeight: 40, marginRight: 8 },

  actionBtn: {
    marginTop: tokens.spacing.md,
  },
  buttonDisabled: { opacity: 0.45 },

  detectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryAlpha(0.12),
    borderWidth: 1,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 10,
  },
  detectButtonText: { color: theme.colors.primarySoft, fontWeight: '700', fontSize: fonts.scaled(13), marginLeft: 6 },
  // 模型输入行里的「搜索」按钮：与「添加」并排，稍作间距。
  modelSearchButton: { marginLeft: 8 },

  fieldHint: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18), marginBottom: 4 },
  savedHint: { color: theme.colors.primaryMuted, fontSize: fonts.scaled(12), marginTop: 8 },

  selectButton: {
    flexDirection: 'row',
    backgroundColor: theme.colors.primary,
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginLeft: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectButtonGhost: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  selectButtonText: { color: theme.colors.primaryContrast, fontWeight: '700' },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 18 },
  capabilityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  personaActions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: tokens.spacing.sm },
  personaAddChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderStyle: 'dashed',
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  personaAddText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(13), marginLeft: 4 },
  samplingRight: { flexDirection: 'row', alignItems: 'center' },
  samplingInput: {
    backgroundColor: theme.colors.surface,
    color: theme.colors.text,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    fontSize: fonts.scaled(14),
    minWidth: 84,
    marginRight: 10,
    textAlign: 'right',
  },
  thinkingDisplayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  thinkingDisplayChips: { flexDirection: 'row', alignItems: 'center' },
  capabilityLabel: { color: theme.colors.textMuted, fontSize: fonts.scaled(14), flex: 1, marginRight: 12 },
  modelChips: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  modelChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    paddingLeft: 10,
    paddingRight: 8,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
    maxWidth: '100%',
  },
  modelChipActive: {
    backgroundColor: theme.colors.primaryAlpha(0.25),
    borderColor: theme.colors.primary,
  },
  modelChipMain: { maxWidth: 180, marginRight: 6 },
  modelChipText: { color: theme.colors.textMuted, fontSize: fonts.scaled(13) },
  modelChipTextActive: { color: theme.colors.text, fontWeight: '700' },
  thinkingFormatRow: { flexDirection: 'row', marginTop: 8, marginBottom: 4 },
  formatChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    marginRight: 8,
  },
  formatChipActive: { backgroundColor: theme.colors.primaryAlpha(0.25), borderColor: theme.colors.primary },
  formatChipText: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), fontWeight: '700' },
  formatChipTextActive: { color: theme.colors.primarySoft },

  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  linkLeft: { flexDirection: 'row', alignItems: 'center' },
  linkText: { color: theme.colors.textMuted, fontSize: fonts.scaled(15), marginLeft: 10 },
  linkRight: { flexDirection: 'row', alignItems: 'center' },
  linkValue: { color: theme.colors.textFaint, fontSize: fonts.scaled(13), marginRight: 6 },

  avatarRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
  avatarBox: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.surface,
    overflow: 'hidden',
    marginRight: 12,
    borderWidth: 2,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
  },
  avatarImg: { width: 56, height: 56, borderRadius: 28 },
  avatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.primaryAlpha(0.14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholderText: { color: theme.colors.primarySoft, fontSize: fonts.scaled(20), fontWeight: '800' },
  imageActions: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  smallButton: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.primaryMutedAlpha(0.45),
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginRight: 12,
  },
  smallButtonText: { color: theme.colors.primarySoft, fontWeight: '700', fontSize: fonts.scaled(13) },
  removeText: { color: theme.colors.dangerSoft, fontWeight: '700' },
  versionText: { color: theme.colors.textMuted, fontSize: fonts.scaled(13), fontWeight: '600' },
  modelChipCaps: { paddingHorizontal: 4, paddingVertical: 2, marginRight: 2 },
  secretRow: { flexDirection: 'row', alignItems: 'center' },
  secretInput: { flex: 1 },
  secretToggle: { paddingLeft: 10, paddingVertical: 8 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'center',
    padding: 24,
  },
  modalSheet: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: tokens.radius.lg,
    padding: tokens.metrics.cardPadding,
    maxHeight: '70%',
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.divider,
    ...tokens.elevation(2, theme),
  },
  modalTitle: { color: theme.colors.text, fontSize: fonts.scaled(16), fontWeight: '800', marginBottom: 12 },
  modalList: { maxHeight: 360 },
  modalListContent: { paddingBottom: tokens.spacing.xs },
  modalRow: {
    backgroundColor: theme.colors.surface,
    borderRadius: tokens.radius.md,
    paddingVertical: tokens.spacing.sm + 2,
    paddingHorizontal: tokens.spacing.md,
    marginBottom: tokens.spacing.sm,
    borderWidth: tokens.border.thin,
    borderColor: theme.colors.surfaceBorder,
  },
  modalRowText: { color: theme.colors.textMuted },
  apiKeyLinkRow: { alignItems: 'flex-end', marginTop: 6 },
  apiKeyLink: { color: theme.colors.primarySoft, fontSize: fonts.scaled(13), fontWeight: '700' },
  vendorEditorNote: {
    color: theme.colors.textFaint,
    fontSize: fonts.scaled(12),
    lineHeight: fonts.scaled(18),
    marginTop: 6,
  },
  vendorList: { maxHeight: 420 },
  vendorSectionLabel: {
    color: theme.colors.primaryMuted,
    fontSize: fonts.scaled(12),
    fontWeight: '800',
    marginTop: 10,
    marginBottom: 8,
    letterSpacing: 0.4,
  },
  vendorRow: {
    backgroundColor: theme.colors.surface,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  vendorRowDisabled: { opacity: 0.5 },
  vendorRowHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  vendorName: { color: theme.colors.text, fontSize: fonts.scaled(14), fontWeight: '700', flex: 1, marginRight: 8 },
  vendorNameDisabled: { color: theme.colors.textMuted },
  vendorCategory: { color: theme.colors.primarySoft, fontSize: fonts.scaled(11), fontWeight: '700' },
  vendorBaseUrl: { color: theme.colors.textMuted, fontSize: fonts.scaled(12), marginBottom: 3 },
  vendorNote: { color: theme.colors.textFaint, fontSize: fonts.scaled(12), lineHeight: fonts.scaled(18) },
});
