// 存储门面（过渡期兼容层，2026-10-07 快赢1 起退役为纯转发）。
//
// 约定（单一入口）：
// - **应用代码一律直接 import 对应的 storage/<域>.js 模块**，不再经本文件；
// - 本文件只剩两个职责：
//   1. 测试加载器入口——tests/characterStorage.test.mjs 等把本文件经 Babel 转
//      CJS 后 Module._compile，并靠 Module._load 拦截统一给 storage/* 打桩；
//   2. 大迁移过渡期的 re-export（待领域迁入 features 后删除——七阶段计划 Stage 6）。
// - 新代码从本文件导入会被 scripts/guard-structure.mjs 的门面导入禁令拦下。
//
// 跨域编排也已迁出：saveCharacterState → storage/characterState.js，
// 孤儿媒体回收 → storage/orphanMedia.js。

export { markMediaWrite } from './storage/mediaProtection.js';
export {
  LOCATION_KEY,
  PLACE_LIMIT,
  getLocationSettings,
  normalizeLocationSettings,
  normalizePlace,
  removePlace,
  saveLocationSettings,
  updateLocationSettings,
  upsertPlace,
} from './storage/location.js';
export { detachCharacterFromWorldMap, getWorldMap, getWorldMapStatus, updateWorldMap } from './storage/worldMap.js';
export {
  deleteDiariesForCharacterDeletion,
  getDiaries,
  getDiariesStatus,
  getDiarySettings,
  saveDiaries,
  saveDiarySettings,
  updateDiaries,
} from './storage/diary.js';
export {
  deleteMomentsBySessionIds,
  deleteMomentsForCharacterDeletion,
  getMoments,
  getMomentsSettings,
  getMomentsStatus,
  getProactiveSettings,
  makeProactiveSlotId,
  PROACTIVE_MODES,
  saveMoments,
  saveMomentsSettings,
  saveProactiveSettings,
  bindProactiveSlotSession,
  updateMoments,
} from './storage/moments.js';
export { deleteStickers, getStickers, reorderStickers, saveSticker } from './storage/stickers.js';
export {
  DISCLAIMER_VERSION,
  SAMPLING_FIELDS,
  THINKING_DISPLAYS,
  THINKING_LEVELS,
  MUSIC_CLIP_SECONDS,
  MUSIC_CLIP_SAMPLE_RATES,
  DEFAULT_MUSIC_CLIP,
  UI_SECTION_IDS,
  acknowledgeDisclaimer,
  completeOnboarding,
  getAppearanceSettings,
  getChatOptions,
  getEnabledPlugins,
  getImageGenSettings,
  getInlineImageSettings,
  getMemorySummarySettings,
  getMusicClipSettings,
  getPlugins,
  getSamplingSettings,
  getThinkingSettings,
  getTranscriptionSettings,
  getTtsSettings,
  getUiSections,
  isDisclaimerAcknowledged,
  isOnboardingDone,
  patchAppearanceSettings,
  saveAppearanceSettings,
  saveChatOptions,
  saveImageGenSettings,
  saveInlineImageSettings,
  saveMemorySummarySettings,
  saveMusicClipSettings,
  savePlugins,
  saveSamplingSettings,
  saveThinkingSettings,
  saveTranscriptionSettings,
  saveTtsSettings,
  saveUiSections,
} from './storage/settings.js';
export {
  WORKSPACE_KEY,
  WORKSPACE_CHANGES_KEY,
  WORKSPACE_CHATS_KEY,
  WORKSPACE_CHANGE_LIMIT,
  WORKSPACE_CHAT_LIMIT_SIZE,
  WORKSPACE_CHAT_MESSAGE_LIMIT_SIZE,
  appendWorkspaceChange,
  appendWorkspaceChatMessages,
  clearWorkspaceChanges,
  clearWorkspaceChats,
  createWorkspaceChat,
  deleteWorkspaceChat,
  getWorkspaceChanges,
  getWorkspaceChats,
  getWorkspaceSettings,
  normalizeWorkspaceChange,
  patchWorkspaceSettings,
  saveWorkspaceSettings,
  setActiveWorkspaceChat,
} from './storage/workspace.js';
export {
  clearGithubMcpCredentials,
  connectGithubMcpWithToken,
  createGithubMcpSessionFromSettings,
  GITHUB_MCP_KEY,
  getGithubMcpSettings,
  normalizeGithubMcpSettings,
  patchGithubMcpSettings,
  refreshGithubMcpToolCatalog,
} from './storage/githubMcp.js';
export {
  DEFAULT_MAX_OUTPUT_TOKENS,
  capabilitiesForModel,
  createApiConfig,
  getActiveApiConfig,
  getActiveModel,
  getApiConfigs,
  normalizeCapabilityEntry,
  rawCapabilityForModel,
  saveApiConfigs,
} from './storage/apiConfigs.js';
export {
  deleteLocalModelItem,
  getActiveLocalModel,
  getLocalModelIndex,
  getLocalModelItem,
  getLocalModelSettings,
  localModelItemKey,
  rebuildLocalModelIndex,
  saveLocalModelItem,
  saveLocalModelSettings,
} from './storage/localModels.js';
export {
  USER_PROFILE_KEY,
  createPersona,
  deletePersona,
  getActivePersonaId,
  getPersonas,
  getUserProfile,
  getUserProfileStatus,
  saveUserProfile,
  setActivePersonaId,
} from './storage/personas.js';
export {
  createGlobalPresetId,
  getEnabledGlobalPresetPrompts,
  getGlobalPresetSettings,
  getGlobalPresets,
  saveGlobalPresetSettings,
  saveGlobalPresets,
} from './storage/globalPresets.js';
export {
  createVectorConfig,
  getVectorIndex,
  clearVectorIndex,
  getVectorIndexStatus,
  getVectorMemoryConfig,
  getVectorMemorySettings,
  removeVectorIndexForMessage,
  removeVectorIndexForMessages,
  removeVectorIndexForSession,
  removeVectorIndexForSessions,
  saveVectorIndex,
  saveVectorMemoryConfig,
  saveVectorMemorySettings,
  updateVectorIndex,
} from './storage/vector.js';
export { getAffinityStatus, saveAffinity } from './storage/affinity.js';
export { exportBackup, importBackup } from './storage/backup.js';
export {
  DEFAULT_CHARACTER,
  clearCharacterEditDraft,
  getActiveCharacterId,
  getCharacterLibrary,
  hasShownDefaultGreeting,
  isCharacterLibraryWriteBlocked,
  markDefaultGreetingShown,
  saveCharacterEditDraft,
  saveCharacterLibrary,
  setActiveCharacterId,
  sortCharacters,
  takeCharacterEditDraft,
} from './storage/characters.js';
export {
  clearCardForge,
  getCardForge,
  getCardForgeStatus,
  saveCardForge,
} from './storage/cardForge.js';
export {
  appendSessionSummary,
  clearSessionDraft,
  cloneSession,
  collectChatImageFiles,
  collectVoiceFiles,
  createGroupSession,
  deleteSession,
  deleteSessions,
  findOrphanSessions,
  getActiveSessionId,
  getMessagesBySession,
  getMessagesBySessionStatus,
  getSessionDraft,
  getSessionSummaries,
  getSessionSummariesStatus,
  getSessionSummaryRevision,
  getSessions,
  invalidateSessionSummaries,
  isSessionSummaryRevisionCurrent,
  markSessionModel,
  migrateLegacyMessages,
  reconcileVectorIndexes,
  reconcileWorldMemories,
  resetSessionSummaries,
  restoreSession,
  saveMessagesBySession,
  appendProactiveMessage,
  saveSessionDraft,
  saveSessions,
  searchMessages,
  setActiveSessionId,
  setSessionAgentMode,
  setProtectedChatImageUris,
  setProtectedVoiceUris,
  setSessionGreetingSelected,
  setSessionPinned,
  setSessionSummarizedUpTo,
  startNewSession,
  updateSessionInfo,
  updateSessionMemberProfiles,
  whenSessionMutationsSettled,
} from './storage/sessions.js';
export { saveCharacterState } from './storage/characterState.js';
export {
  collectStickerImageFiles,
  collectAvatarImageFiles,
  collectOrphanImageFiles,
} from './storage/orphanMedia.js';
