export const TUTORIAL_SECTIONS = [
  {
    id: 'chat',
    title: '聊天',
    icon: 'chatbubbles-outline',
    intro: '与角色对话的主界面，消息、附件与操作都集中在这里。',
    items: [
      { name: '发送消息', where: '底部输入框右侧的箭头按钮', usage: '输入内容后点击发送，助手开始回复。' },
      { name: '停止生成', where: '生成过程中发送按钮变为停止', usage: '点击可中断正在生成的回复。' },
      { name: '新建对话', where: '顶部「新建」按钮', usage: '为当前角色开启一段新对话，旧对话保留在「记忆」中。' },
      { name: '更多菜单', where: '顶部「⋯」按钮', usage: '展开公告、模型、思考、定位、搜索、总结与设置。' },
      { name: '切换角色', where: '顶部左侧的角色头像与名称', usage: '点击弹出角色列表，选择后切换到该角色。' },
      { name: '语音播报', where: '顶部「播报开 / 播报关」按钮', usage: '控制是否朗读助手回复。' },
      { name: '引用消息', where: '长按或点击消息下方的操作行', usage: '引用某条消息后再发送，引用内容会一并提交。' },
      { name: '清空聊天', where: '输入栏附近的操作入口', usage: '清空当前会话的消息，需二次确认。' },
      { name: '复制文本', where: '消息操作行的「复制」', usage: '把消息内容复制到剪贴板。' },
      { name: '消息定位', where: '「⋯」菜单中的「定位」', usage: '拖动滑块快速跳转到会话任意位置。' },
    ],
  },
  {
    id: 'memory',
    title: '记忆',
    icon: 'albums-outline',
    intro: '管理历史会话，随时回到过去的对话。',
    items: [
      { name: '会话列表', where: '记忆页主列表', usage: '展示每个会话的头像、角色名、摘要与时间。' },
      { name: '继续对话', where: '点击任意会话行', usage: '切换到该角色与会话并进入聊天页。' },
      { name: '置顶', where: '会话行右侧的星标按钮', usage: '置顶会话排在列表最前。' },
      { name: '克隆', where: '会话行右侧的克隆按钮', usage: '复制一份会话，消息 id 重新生成。' },
      { name: '删除', where: '会话行右侧的删除按钮', usage: '删除会话及其消息，需二次确认。' },
      { name: '批量删除', where: '顶部「编辑」进入多选模式', usage: '勾选多个会话后统一点击删除。' },
      { name: '搜索历史', where: '记忆页顶部搜索入口', usage: '跨全部会话按关键词检索并跳转定位。' },
    ],
  },
  {
    id: 'character',
    title: '角色',
    icon: 'people-outline',
    intro: '创建、编辑与导入角色，塑造你的 AI 伙伴。',
    items: [
      { name: '切换角色', where: '角色库列表点击角色', usage: '把该角色设为当前角色并同步会话。' },
      { name: '新建角色', where: '顶部新建按钮', usage: '创建一个空白角色后进入编辑。' },
      { name: '编辑角色', where: '角色页字段区块', usage: '修改名称、头像、背景、人设、描述、性格、标签、世界书与正则。' },
      { name: '导入角色卡', where: '「基本信息」中的「导入角色卡」', usage: '支持 PNG 或 JSON 格式的 V2/V3 角色卡。' },
      { name: '导出角色卡', where: '「基本信息」中的「导出角色卡」', usage: '把当前角色导出为角色卡文件。' },
      { name: '创建群聊', where: '角色页顶部「群聊」按钮', usage: '多选 2-8 个角色创建群聊会话。' },
      { name: '搜索与置顶', where: '角色库顶部', usage: '按名称与标签搜索，星标置顶常用角色。' },
      { name: '多选删除', where: '角色库「编辑」模式', usage: '多选角色批量删除，全选需输入确认。' },
    ],
  },
  {
    id: 'settings',
    title: '设置',
    icon: 'settings-outline',
    intro: '配置 API、生成参数、人设、外观与扩展能力。',
    items: [
      { name: 'API 配置', where: '「API 配置」卡片', usage: '填写服务地址、模型与密钥，密钥仅存本机。' },
      { name: '全局预设', where: '「全局配置」中的「全局预设」入口', usage: '管理并开启注入提示词的预设。' },
      { name: '记忆总结', where: '预设面板中的记忆总结设置', usage: '开启自动总结并设置触发阈值。' },
      { name: '生成参数', where: '「生成参数」卡片', usage: '按需开启最大令牌、温度、top-p 与 top-k。' },
      { name: '用户人设', where: '「用户人设」卡片', usage: '维护多套用户身份并切换当前人设。' },
      { name: '向量记忆', where: '「向量记忆」卡片', usage: '配置 embedding 服务以启用语义记忆检索。' },
      { name: '外观', where: '「外观」卡片', usage: '切换主题与字体缩放。' },
      { name: '联网搜索 / 语音播报', where: '「全局配置」中的对应入口', usage: '配置联网搜索与语音播报服务。' },
      { name: '免责条款', where: '「关于」中的「免责条款」', usage: '随时重新查看免责声明。' },
    ],
  },
];

export default TUTORIAL_SECTIONS;
