export const TTS_MAX_CHARS = 800;

const BEARER_FIELDS = [
  { key: 'baseUrl', label: '接口地址', placeholder: 'https://example.com/v1/audio/speech' },
  { key: 'apiKey', label: 'API Key', secret: true, placeholder: 'sk-...' },
  { key: 'model', label: '模型名', optional: true, placeholder: 'tts-1' },
  { key: 'voice', label: '音色', optional: true, placeholder: 'alloy' },
  { key: 'speed', label: '语速', optional: true, placeholder: '1.0' },
];

export const TTS_PROVIDERS = [
  {
    id: 'system',
    label: '系统引擎',
    engine: 'system',
    fields: [
      { key: 'voice', label: '音色', optional: true, placeholder: '留空使用默认' },
      { key: 'speed', label: '语速', optional: true, placeholder: '0.5 - 2.0' },
    ],
    voices: [],
    timeoutMs: 0,
    retries: 0,
  },
  {
    id: 'xiaomi-mimo',
    label: '小米 MiMo',
    apiKeyUrl: 'https://platform.xiaomimimo.com',
    // 官方 API 域名为 api.xiaomimimo.com（平台首页 platform.xiaomimimo.com 已核实）。
    // /v1/audio/speech 为官方兼容端点（推荐走 /v1/chat/completions，但本引擎为
    // 声明式 audio/speech 形态，选兼容端点零引擎改动）。
    baseUrl: 'https://api.xiaomimimo.com/v1/audio/speech',
    method: 'POST',
    // MiMo 鉴权用 api-key 请求头，不是 OpenAI 风格的 Authorization: Bearer。
    auth: { type: 'header', keyName: 'api-key' },
    textField: 'input',
    voiceField: 'voice',
    speedField: 'speed',
    formatField: 'response_format',
    // 兼容端点返回 JSON，音频 base64 位于 message.audio.data，不是音频二进制流。
    response: { mode: 'base64', path: 'message.audio.data' },
    fields: [
      { key: 'baseUrl', label: '接口地址', placeholder: 'https://api.xiaomimimo.com/v1/audio/speech' },
      { key: 'apiKey', label: 'API Key', secret: true, placeholder: '在开放平台控制台获取' },
      { key: 'model', label: '模型名', optional: true, placeholder: '以官方文档为准' },
      { key: 'voice', label: '音色', optional: true, placeholder: '以官方音色列表为准' },
      { key: 'speed', label: '语速', optional: true, placeholder: '1.0' },
    ],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
  {
    id: 'siliconflow',
    label: '硅基流动',
    apiKeyUrl: 'https://cloud.siliconflow.cn/account/ak',
    baseUrl: 'https://api.siliconflow.cn/v1/audio/speech',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    textField: 'input',
    voiceField: 'voice',
    speedField: 'speed',
    formatField: 'response_format',
    response: { mode: 'binary' },
    fields: BEARER_FIELDS,
    voices: ['FunAudioLLM/CosyVoice2-0.5B:alex', 'FunAudioLLM/CosyVoice2-0.5B:anna'],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
  {
    id: 'iflytek-spark',
    label: '讯飞星火',
    apiKeyUrl: 'https://console.xfyun.cn/services/bmx1',
    baseUrl: 'wss://tts-api.xfyun.cn/v2/tts',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization' },
    signer: 'iflytek',
    textField: 'text',
    voiceField: 'vcn',
    speedField: 'speed',
    formatField: 'aue',
    response: { mode: 'base64', path: 'data.audio' },
    fields: [
      { key: 'appId', label: 'APPID', placeholder: '应用 ID' },
      { key: 'apiKey', label: 'APIKey', secret: true, placeholder: 'API Key' },
      { key: 'appSecretKey', label: 'APISecret', secret: true, placeholder: 'API Secret' },
      { key: 'voice', label: '音色', optional: true, placeholder: 'xiaoyan' },
      { key: 'speed', label: '语速', optional: true, placeholder: '50' },
    ],
    timeoutMs: 30000,
    retries: 0,
  },
  {
    id: 'stepfun',
    label: '阶跃星辰',
    apiKeyUrl: 'https://platform.stepfun.com',
    baseUrl: 'https://api.stepfun.com/v1/audio/speech',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    textField: 'input',
    voiceField: 'voice',
    speedField: 'speed',
    formatField: 'response_format',
    response: { mode: 'binary' },
    fields: BEARER_FIELDS,
    voices: ['cixingnansheng', 'zhaixiaowai'],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
  {
    id: 'tencent-cloud',
    label: '腾讯云',
    apiKeyUrl: 'https://console.cloud.tencent.com/cam/capi',
    baseUrl: 'https://tts.tencentcloudapi.com',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization' },
    signer: 'tencent',
    textField: 'Text',
    voiceField: 'VoiceType',
    speedField: 'Speed',
    formatField: 'Codec',
    response: { mode: 'base64', path: 'Response.Audio' },
    fields: [
      { key: 'appId', label: 'SecretId', placeholder: 'SecretId' },
      { key: 'apiKey', label: 'SecretKey', secret: true, placeholder: 'SecretKey' },
      { key: 'region', label: '地域', optional: true, placeholder: 'ap-guangzhou' },
      { key: 'voice', label: '音色 ID', optional: true, placeholder: '101001' },
      { key: 'speed', label: '语速', optional: true, placeholder: '0' },
    ],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
  {
    id: 'aliyun',
    label: '阿里云百炼',
    apiKeyUrl: 'https://bailian.console.aliyun.com/',
    baseUrl: 'https://nls-gateway-cn-shanghai.aliyuncs.com/stream/v1/tts',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer ' },
    // 阿里云 NLS 网关要求 appkey 作为查询参数；原声明收集了 AppKey 却从不发送。
    queryFields: [{ name: 'appkey', from: 'appId' }],
    textField: 'text',
    voiceField: 'voice',
    speedField: 'speech_rate',
    formatField: 'format',
    response: { mode: 'binary' },
    fields: [
      { key: 'apiKey', label: 'Token', secret: true, placeholder: '访问令牌' },
      { key: 'appId', label: 'AppKey', optional: true, placeholder: '应用 AppKey' },
      { key: 'voice', label: '音色', optional: true, placeholder: 'xiaoyun' },
      { key: 'speed', label: '语速', optional: true, placeholder: '0' },
    ],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
  {
    id: 'baidu',
    label: '百度智能云',
    apiKeyUrl: 'https://console.bce.baidu.com/ai-engine/old/#/ai/speech/app/list',
    baseUrl: 'https://tsn.baidu.com/text2audio',
    method: 'POST',
    auth: { type: 'token', keyName: 'access_token', tokenUrl: 'https://aip.baidubce.com/oauth/2.0/token', tokenFields: { grant_type: 'client_credentials' }, tokenPath: 'access_token', tokenTtlSec: 2592000 },
    textField: 'tex',
    voiceField: 'per',
    speedField: 'spd',
    formatField: 'aue',
    response: { mode: 'binary' },
    fields: [
      { key: 'apiKey', label: 'API Key', secret: true, placeholder: 'API Key' },
      { key: 'appSecretKey', label: 'Secret Key', secret: true, placeholder: 'Secret Key' },
      { key: 'voice', label: '发音人', optional: true, placeholder: '0' },
      { key: 'speed', label: '语速', optional: true, placeholder: '5' },
    ],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
  {
    id: 'volcano',
    label: '火山引擎',
    apiKeyUrl: 'https://console.volcengine.com/speech/new/setting/apikeys',
    baseUrl: 'https://openspeech.bytedance.com/api/v1/tts',
    method: 'POST',
    auth: { type: 'header', keyName: 'Authorization', prefix: 'Bearer;' },
    signer: 'volcano',
    textField: 'text',
    voiceField: 'voice_type',
    speedField: 'speed_ratio',
    formatField: 'encoding',
    response: { mode: 'base64', path: 'data' },
    fields: [
      { key: 'appId', label: 'AppID', placeholder: '应用 ID' },
      { key: 'apiKey', label: 'Access Token', secret: true, placeholder: '访问令牌' },
      { key: 'voice', label: '音色', optional: true, placeholder: 'BV001_streaming' },
      { key: 'speed', label: '语速', optional: true, placeholder: '1.0' },
    ],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    apiKeyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    baseUrl: 'https://api.minimax.chat/v1/t2a_v2',
    method: 'POST',
    // MiniMax 同时需要两种凭据：GroupId 进查询串，API Key 进 Bearer 头。
    // 原声明只有 query 认证，导致用户填的 API Key 从不发送、请求必然 401。
    auth: { type: 'query', keyName: 'GroupId', bearer: true },
    textField: 'text',
    voiceField: 'voice_setting.voice_id',
    speedField: 'voice_setting.speed',
    formatField: 'audio_setting.format',
    response: { mode: 'base64', path: 'data.audio' },
    fields: [
      { key: 'apiKey', label: 'API Key', secret: true, placeholder: 'Bearer Token' },
      { key: 'appId', label: 'GroupId', placeholder: 'GroupId' },
      { key: 'model', label: '模型名', optional: true, placeholder: 'speech-01-turbo' },
      { key: 'voice', label: '音色', optional: true, placeholder: 'male-qn-qingse' },
      { key: 'speed', label: '语速', optional: true, placeholder: '1.0' },
    ],
    timeoutMs: 30000,
    retries: 1,
    custom: true,
  },
];

export function getTtsProvider(id) {
  return TTS_PROVIDERS.find(provider => provider.id === id) || TTS_PROVIDERS[0];
}
